### ISSUE TITLE
unable to login to gmail and RTM on same page

### ISSUE THREAD

**Issue by drasch** [hultmann/multifox#1]
I use Google Apps Gmail, and then I have a Remember The Milk gadget on the same page.  It seems with MultiFox, I'm unable to get logged into both of these so I can see my todos and my email on the same page.  Any help would be appreciated!

**Comment by hultmann** [comment]
Currently Multifox 2 doesn't use any login for widgets, frames/iframes etc.

This will be fixed (fixed at least partially) in the next beta.

**Comment by drasch** [comment]
Great!  thanks for the follow-up.  Awesome tool.  I discovered when looking at plugins for Firefox 4.  I've demoed it to 3-4 people here at the office and all they can say is "wow".

**Comment by hultmann** [comment]
Did Multifox 2 beta 2 fix this?

**Comment by drasch** [comment]
indeed, working!
