### ISSUE TITLE
v2.0b2 Limited amount of profiles? Youtube example

### ISSUE THREAD

**Issue by RubenMT** [hultmann/multifox#10]
Hello, and thanks for being here

Do you know how many YouTube accounts can Multifox (BETA) 2.0b2 handle? Look what happened to me when logging in multiple accounts, it doesn't allow me to do it.

What I did:
I logged in multiple different YouTube users (n1, n2, n3, n4, n5, n6) by clicking 'New Account' in different tabs and singing in, user and pass, ticking the 'Stay signed in' box. The profiles/accounts 'accumulated' in the Multifox list, allowing me to swap between them. However, when I logged in the account n7 - or 7th account-  the accounts n1, n2 and n3 'disappear' from the list of profiles available.

The maximum amount of profiles/accounts I've been able to have listed at the same time are 6. When I keep adding accounts, the old ones disappear, with no apparent order.

Is there a limit? What am I doing wrong?

Thanks!

Ruben Moutinho

**Comment by RubenMT** [comment]
I am using Firefox 4.0.1

**Comment by hultmann** [comment]
Probably related to bug #7. Multifox can handle infinite accounts.

**Comment by RubenMT** [comment]
Try and log with 10 different accounts of youtube to check if it's solved when you do changes :) I can volunteer for this.

**Comment by hultmann** [comment]
It seems the number the accounts don't care, cookies disappear randomly.

There are other bugs about this issue, please follow #16 for any progress.
