### ISSUE TITLE
Multifox 1.x broken on Aurora & Nightly

### ISSUE THREAD

**Issue by LordJZ** [hultmann/multifox#101]
About a week ago, before the release of FF 20, Multifox 1.3.5 stopped working on Nightly (currently it's Aurora).

Switching the profile (by opening a new window or changing it in an existing window) yields nothing -- the cookies used are still for the default profile.

**Comment by hultmann** [comment]
Thanks for the report. Right now I'm working on 1.3.6 (remove Multifox from private windows). It would be nice to have this fixed too. :)

**Comment by LordJZ** [comment]
Hey, thanks!

**Comment by LordJZ** [comment]
It's working, thanks!
