### ISSUE TITLE
"Open in New Identity Profile" is not visible with latest FF version

### ISSUE THREAD

**Issue by akbarmunir** [hultmann/multifox#102]
My Firefox recently got upgraded to the version 20.0.1. But now I can not find "Open in New Identity Profile" option in File menu. Even the shortcut key (which perhaps was Ctrl + Shift + T) does not work. I have even tried to use the Multifox Beta 2, however the same problem persists. Am I missing some setting?

**Comment by hultmann** [comment]
Multifox 1.3.6 is unavailable on private windows. Is it the case?

**Comment by akbarmunir** [comment]
Not only in private window, but in regular window too. I have been using Multifox on FF with Private Browsing permanently enabled. But the "New Identity Profile" was always displayed in File menu. Now with the new upgrade, no matter whether I keep the private browsing mode on or off, and even for a new private window, this option is nowhere to be seen. This is same with both 1.3.6 and with Beta 2

**Comment by hultmann** [comment]
Does about:multifox URL work?

**Comment by akbarmunir** [comment]
Yes. It shows the version 1.3.6. Attached is the snapshot.

BTW I am using Windows 7 64-bit Enterprise.

![Multifox Error](https://f.cloud.github.com/assets/4140310/377522/f706dff8-a4c3-11e2-930c-b421aa44c25e.jpg)

**Comment by Tekonopop-57** [comment]
.My Firefox recently got upgraded to the version 20.0.1. as well, and now I can not find "Open in New Identity Profile" option in File menu. Multifox appears in the add-ons, but no where on the browser.
 I also am using Windows 7 64-bit operating system.

**Comment by hultmann** [comment]
ops, I didn't realize what "Private Browsing permanently" means. :)

unfortunately: private browsing=no Multifox

There is nothing to be done (due to changes in Firefox 20+).

I'll update Multifox to make this limitation clear.

**Comment by akbarmunir** [comment]
That's not correct. Even if you turn the private browsing mode on or off, it does not matter. The menu option is permanently gone, due to some bug. This was not the behaviors earlier. I have been using FF in private browsing mode for over 2 years now and never have Multifox given me this problem.

**Comment by Tekonopop-57** [comment]
So no MultiFox for us unless we downgrade our browser

On Sun, Apr 14, 2013 at 4:21 PM, Jeferson Hultmann <notifications@github.com

**Comment by LordJZ** [comment]
Hey guys,
I've checked [Multifox 1.3.6](http://br.mozdev.org/multifox/) in FF 20 (release) and FF 23 (nightly) — everything works perfectly!
![ff20multifox2](https://f.cloud.github.com/assets/32092/382453/b8ba8d26-a5f9-11e2-8f4d-4e561f40281a.png)![ff20multifox](https://f.cloud.github.com/assets/32092/382455/bfca3cba-a5f9-11e2-9909-61a6eb17ec9b.png)
So you must be having some addon conflict.

**Comment by hultmann** [comment]
Folks (especially akbarmunir), please try this version:

http://code.google.com/p/multifox/downloads/detail?name=multifox-1.3.7pre.xpi&can=1&q=

**Comment by akbarmunir** [comment]
Thanks hultmann. This works fine. However, there is one behavior change. If I have setting "Never Remember History" in FF, and try to open a new identity, it gives me error that new identities can not be opened from private window, and that I should try again from a regular window. However if I set the history to "Remember History", it works as expected.

I had Multifox working with FF in "Never Remember History" mode before this version. Has something changed in FF that is preventing Multifox now?

**Comment by hultmann** [comment]
"Never Remember History" actually means "All windows are private". Due to changes in Firefox 20, extensions are unable to handle private cookies.

**Comment by hultmann** [comment]
Those interested in private windows may want to follow bug #110.
