### ISSUE TITLE
Issue at AMO pages

### ISSUE THREAD

**Issue by tbs** [hultmann/multifox#103]
When logged to Mozilla addons website I got error bellow:

![Error Console](https://f.cloud.github.com/assets/768954/401904/48ab9938-a8ee-11e2-88dc-bf5a081036c1.png)

Example, https://addons.mozilla.org/en-US/firefox/addon/betterstop/

Sad this addon doesn't receive the attention it deserves.

**Comment by hultmann** [comment]
I don't see this bug. What version of Firefox are you using?

**Comment by tbs** [comment]
Firefox Nightly, confirmed with a fresh profile.

**Comment by hultmann** [comment]
Yes, https://bugzilla.mozilla.org/show_bug.cgi?id=600307 seems to be the culprit.

**Comment by tbs** [comment]
yeah, it is breaking many websites here.

You will release a fix soon or better I disabled Multifox for now?

**Comment by hultmann** [comment]
If there is a trivial fix, this weekend. Otherwise, many weeks.

**Comment by hultmann** [comment]
I believe it's fixed. Please try:
http://code.google.com/p/multifox/downloads/detail?name=multifox-2.0b8pre.xpi&can=2&q=#makechanges

**Comment by tbs** [comment]
Very nice! Working like a charm!

Thank you! Valeu Hultmann! Tenho mais de 50 extensões, mas largaria todas pela MultiFox, a mais importante que já testei em anos.

**Comment by hultmann** [comment]
Cool! I've just released it as v2.0b8.

**Comment by hultmann** [comment]
Multifox 1.3.8 has been released to fix this.
