### ISSUE TITLE
Can you make it open multiple Private Windows?

### ISSUE THREAD

**Issue by mailinglists35** [hultmann/multifox#110]
As mozilla devs are not having this on track (https://bugzilla.mozilla.org/show_bug.cgi?id=463027#c140), do you think is it technically possible to enhance MF to open multiple PB windows?
Thanks!

**Comment by hultmann** [comment]
Technically possible? Yes. But the code would need to duplicate cookies logic to choose what to save or send, while respecting the 3rd-party prefs.

Private windows are second class citizens anyway (they do not support IndexedDB), so for now they are not worth the time.

I will wait for https://bugzilla.mozilla.org/show_bug.cgi?id=777620 to be fixed, it seems it will help to fix Multifox.

**Comment by mailinglists35** [comment]
Many thanks for your answer.
What I'm aiming to do is to login into gmail/facebook/other in a "clear"
sandboxed cookie-free environment (which private browsing seems to be), and
let the normal profile collect regular browsing cookies.

On Tue, Jun 11, 2013 at 4:53 AM, Jeferson Hultmann <notifications@github.com

**Comment by hultmann** [comment]
> sandboxed cookie-free environment (which private browsing seems to be), and let the normal profile collect regular browsing cookies.

The difference between a Multifox profile and private browsing is the private browsing lost its personal data (e.g cookies) after you close all private windows.

Closing as this feature would be out of scope for this project.
