### ISSUE TITLE
limits ? and/or malfunctions?

### ISSUE THREAD

**Issue by caspertone2003** [hultmann/multifox#111]
Hi,
I started using multifox and worked flawlessly with 3 or 4 identity profiles. I tried to go up to 14; it works ok, but when I exit, next restart it looses configuration of 4 of them. If I rebuild them (so, again 14 profiles), after exit and open again, I lost again 4 profiles. If I exit with 4 profiles lost, after restart I loose another4 more ...
It becomes unusable, so I had to step back to other uneffective alternatives; I lost the fantastic functionality of multifox!!

I also tried to use it within virtualbox shared folders, but I received a message that there was delayed writing failure and stopped doing that. Gave similar outcomes as before.

Are there limits to the number of identity profiles? Could these failures depend on the content of the requested urls? Or in the speed of the HD process?
Is there any way to try to locate if this is a failure and how to solve it?

PD: I have mozilla updated to last version (21.0) and multifox also (1.3.8) No other extension running..

Thanks in advance,
CTone

**Comment by hultmann** [comment]
Yes, it's a known bug. I'm working on a fix (related: https://github.com/hultmann/multifox/issues/16#issuecomment-1399420)

I'll have to change the host scheme from
www.google.com.multifox-profile-2

to something like
www.google.com.google-com-2.multifox
