### ISSUE TITLE
Castle Age lap over

### ISSUE THREAD

**Issue by thesteek** [hultmann/multifox#112]
the new changes in the Castle Age game on fb, has some serious issues,ie lapping, not completing info in proper boxes, inability to collect on monster wins. In order to be useful it needs to be fixed.

**Comment by hultmann** [comment]
Is it still an issue?

**Comment by thesteek** [comment]
I dont remember now what the prob was lol. been a while. only prob i am having right now is demi praying on castle age not increasing when i pray for health. dont think that is anythiing you can fix  but thanks anyway.  i do have a prob with ff multifox,  under the multifox tab if i restart my puter and dont use the acct no's ie 1 2  3 4... it will make a thousand of them and i cant get it to clear. if you can tell me how to clear it sure would help.

---

On Thu, 9/18/14, Jeferson Hultmann notifications@github.com wrote:

 Subject: Re: [multifox] Castle Age lap over (#112)
 To: "hultmann/multifox" multifox@noreply.github.com
 Cc: "thesteek" crappieklr@yahoo.com
 Date: Thursday, September 18, 2014, 3:43 PM

 Is it still an issue?

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by hultmann** [comment]
The easiest way to remove all profiles would be uninstalling Multifox then installing again.
