### ISSUE TITLE
Apple I-Cloud Calendar Fails to load

### ISSUE THREAD

**Issue by J-Bird-Medic** [hultmann/multifox#113]
Other features at the icloud.com work but it will not load the #calendar.
I disabled multifox and it works, re-enable and it fails.

https://www.icloud.com/#calendar

Multifox 2.0b7 on FF17.0.1

**Comment by hultmann** [comment]
Is this still an issue?

**Comment by J-Bird-Medic** [comment]
No idea. Stopped using multifox then, Jul 13, 2013.

**Comment by hultmann** [comment]
Sorry for the long delay, I've been busy with fixing some other bugs.
