### ISSUE TITLE
HTML 5 video isn't loading with multifox

### ISSUE THREAD

**Issue by tbs** [hultmann/multifox#114]
Video player in url bellow is not loading if Multifox 2 b8 is active:

http://video.pandodaily.com/H9RK/pandohouse-rock-what-is-bitcoin-super-mario-bros-explains-it-all-in-a-one-minute-video/

Confirmed?

**Comment by hultmann** [comment]
Yes (however it works with 1.x). I think it will be fixed when I remove the Electrolysis-ready implementation in 2.0b (next beta I hope) since it's a source of bugs like this.

**Comment by tbs** [comment]
curious question, why the whitelist doesn't fix this case and other similar?

**Comment by hultmann** [comment]
The DOMWindowCreated event sometimes doesn't provide the document location. So I have to apply the multifox customization because it would be needed later.

**Comment by hultmann** [comment]
I believe it is fixed now (in Multifox and AllAccounts).
