### ISSUE TITLE
Multifox 2 whitelist mode not work with subdomains (third level domains)

### ISSUE THREAD

**Issue by MurzNN** [hultmann/multifox#118]
I have different systems installed on subdomains of one domain.
So mydomain.com is main domain, when i use my login murz
mail.mydomain.com is mail system web interface (it needs logins like user@mydomain.com and I use many logins)
wiki.mydomain.com when I use login korepov and other user logins
crm.mydomain.com when I use  login alexey

I want enable multifox for switching account only for mail.mydomain.com and wiki.mydoimain.com.

Without whitelist mode enabled, multifox save all variants of logins and switch it wrong, so when I login on crm.mydomain.com as alexey, after this switch to wiki.mydomain.com and login as korepov, and after - open crm.mydomain.com  - I see me logouted and in multifox I see korepov session instead of alexey.

So i try enable multifox whitelist mode, in extensions.{42f25d10-4944-11e2-96c0-0b6a95a8daf0}.whitelistMode i write "mail.mydomain.com wiki.mydoimain.com".

But after this I have the same problem, and the new problem - new logins stops itercepting and saving via multifox.

Is multifox works only for second level domain or this is bug in current versions? How I can enable multifox only for third level domains of some domain?

**Comment by hultmann** [comment]
This is the by design behavior and no way to change it. See https://github.com/hultmann/multifox/issues/14#issuecomment-17044292

> Just google.com, not www.google.com or mail.google.com.
