### ISSUE TITLE
New window does not inherit profile

### ISSUE THREAD

**Issue by drothenberger** [hultmann/multifox#121]
Using 2.0.3 and 2.0.2, I find that new windows opened by clicking on a link from a profile >= 2 always use the default profile instead of the profiler of the opener.

This worked fine for me with 1.3.8.

Here's a simple HTML page that demonstrates the problem with a fresh profile and FF 23.0.1. Note that I had to change the option in FF so that new windows are opened in separate windows instead of a tab.

``` html
<!doctype html>
<html>
<head></head>
<body>
<a href='about:blank' target='_blank'>Open</a>
</body>
</html>
```

**Comment by hultmann** [comment]
working on it.

**Comment by hultmann** [comment]
@drothenberger please try
http://code.google.com/p/multifox/downloads/detail?name=multifox-2.0.4b1.xpi&can=2&q=

**Comment by drothenberger** [comment]
@hultmann: 2.0.4b1 solves the problem for me. Thanks for the fast response!
