### ISSUE TITLE
icon on bar

### ISSUE THREAD

**Issue by peekaa** [hultmann/multifox#122]
when i manually remove multifox icon from bar it should stay removed...... Now it comes back atfter restart :-( Thank you
ff 23.0.1.mf 2.0.3. xpsp3.

**Comment by andersjohansson** [comment]
Me too: FF 23.0 (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:23.0) Gecko/20100101 Firefox/23.0).
Multifox 2.0.3.

**Comment by thx1200** [comment]
This is really annoying me.  Is there a workaround or bugfix in the future?

**Comment by hultmann** [comment]
I'll fix it next week.

BTW folks, why do you want to hide the button?

**Comment by thx1200** [comment]
For me, it's just extra clutter.  I don't use multifox often enough to justify having it always on screen for my personal aesthetic.  When I use it, I just go to the main Firefox menu New Tab->New Identity Profile to open a new session.

**Comment by hultmann** [comment]
workaround: move it to a different toolbar and then hide the bar (e.g. addon toolbar)

**Comment by Ackbach** [comment]
The workaround works great for me. Thanks for posting!

**Comment by hultmann** [comment]
it should be fixed: please try http://code.google.com/p/multifox/downloads/detail?name=multifox-2.0.4b1.xpi&can=2&q=

not sure if the button will reappear when a new version is installed. e.g auto-update

**Comment by hultmann** [comment]
2.0.5 will add the button for everyone. It should not happen again.
