### ISSUE TITLE
Multifox 2.0.6: unresponsive script warning

### ISSUE THREAD

**Issue by user7488** [hultmann/multifox#125]
I'm getting unresponsive script warnings when I close a Youtube tab on my profile #2 (haven't tested with #3, ...).

I tried to disable (not uninstall) the other add-ons and restart the browser but problem still happens.
Firefox 25 but also happened on 24.

Script: resource://multifox-xxx/main.js:1627
Script: resource://multifox-xxx/main.js:591

and also (?):
Script: http://s.ytimg.com/yts/jsbin/www-vflNZS3hF/www_base_mod.js:3

**Comment by hultmann** [comment]
Hello,

Does it happen consistently and only with Multifox enabled?

**Comment by user7488** [comment]
Hello :)
Yes, tested now with a new profile, (...)\firefox.exe --no-remote -P new .
On second multifox 'profile', closing an Youtube tab freezes browser instance.

**Comment by andrzej-r** [comment]
I have exactly the same problem. multifox-xxx/main.js:591, also http://s.ytimg.com/yts/jsbin/www-vflV7wvUu/www_common_mod.js:112

Does not seem to happen on a default profile/window.
On other profiles:
- Clearing cookies does not help. 
- Logging out from youtube/google does not help.
- Firefox hangs for ~20 seconds every time I close a tab but not if it is the only tab in a window. Also, does _not_ hang if I press back button or click on another video.

**Comment by hultmann** [comment]
OK folks, I found the bug.
- tab is removed from browser.
- however, code from page is still running.
- a function from Multifox is called (localStorage)
- Multifox is unable to map the origin tab
- web page gets stuck in an infinite loop (due to bad value returned by Multifox)

working in a fix at the moment.

**Comment by dxtr12** [comment]
Waiting for a fix , It's affecting me everytime i close a youtube Tab

**Comment by hultmann** [comment]
Please test, thanks.

http://code.google.com/p/multifox/downloads/detail?name=multifox-2.0.7b1.xpi#makechanges

**Comment by user7488** [comment]
Works fine, thanks!

**Comment by andrzej-r** [comment]
Works well, haven't spotted any issues.
