### ISSUE TITLE
Create new profile

### ISSUE THREAD

**Issue by pintassilgo** [hultmann/multifox#127]
When I click "New (Ctrl+Alt+M)",  it opens another Multifox profile already created, rather than a new profile.

If I have 5 profiles, I need to open 5 windows (one per profile) to finally create the 6th.

How to avoid this inconvenience?

**Comment by hultmann** [comment]
It is not possible. Do you create profiles frequently?

**Comment by pintassilgo** [comment]
Sometimes. Currently I have 7 profiles, but I know I'll need to create much more for the future.

So I will create a few more and let them on the "waiting list"... I hope that this will be enough.

**Comment by pintassilgo** [comment]
\o/

Thanks!

**Comment by hultmann** [comment]
Please try it from https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/
