### ISSUE TITLE
Bad working with two auth systems on one domain or subdomains

### ISSUE THREAD

**Issue by MurzNN** [hultmann/multifox#13]
When I logging in to one system (for example, cms admin page) with login "user1", multifox creates profile "user1".
After I need to the login in new tan to another system in this domain (for example, cms admin page on subfolder, or phpmyadmin) with different username "user2".  I logging in with user2 and multifox creates "user2" profile, login is successfull.

After that I goes back to first tab, multifox shows "user1" profile in url. I go to next page or do the refresh current page and got "access denied", so the session was lost. If I change profile to "user2", session will restored and I see me logged in.

Same problem with subdomains - when I do auth on domain example.com, I lost session on subdomain.example.com.

Can you fix this problem?
Quick solution may be adding domain blacklist in multifox settings, for which session monitoring will be disabled. This is not hard to do and helps me temporary solve my problem.

**Comment by MurzNN** [comment]
How to reproduce this issue:
1. Install some auth system on http://domain.com/
2. Install other auth system on http://domain.com/system2/
3. Open the new tab. Do the auth on http://domain.com/ with login user1. You will successfully auth and see in url multifox profile "user1".
4. Open the new tab and stay previous tab not closed. Do the auth on http://domain.com/system2/ with login user2. You will successfully auth and see in url multifox profile "user2".
5. Go back to first tab, you will see that multifox profile changed to "user1".
6. Do refresh the page or click the link to some other auth page for system on http://domain.com/. You will see "Access denied" message, so auth session "user1" is lost.
7. If you change multifox profile manually to "user2", the session for login "user1" will be restored.

So, normal work is when you on step 6 don't lost the auth session.

**Comment by MurzNN** [comment]
You can reproduce same problem with subdomains - change http://domain.com/system2/ to http://system2.domain.com/ in previous instruction and you got same problems.

**Comment by hultmann** [comment]
This is a bug expected only when systems within the same TLD use the same username (user1=user2 in your example).

Can you can reproduce the issue with a public website?

**Comment by MurzNN** [comment]
What is TLD? I test with different systems (drupal.org CMS and fengoffice.com CRM). 
Usernames are not same, I use korepov and murz, user1 & user2 I select only for example. 
At now I didn't remember any public system with this problem, because they have separate domains, but if you find any with one login on domain and other on subdomain, I think this issue will be reproducible on it. And our company have many local resources in which this issue is reproducible, so I can give you access to our systems for testing, can this help you for testing?

**Comment by hultmann** [comment]
TLD=Top Level Domain (google.com, bbc.co.uk)

Yes, if you provide a system where I can debug this issue it would be very useful!

**Comment by hultmann** [comment]
This was fixed in 2.0b3. Please let me know if there is still an issue.
