### ISSUE TITLE
Identity per tab is gone?

### ISSUE THREAD

**Issue by mpkossen** [hultmann/multifox#130]
I remember running a beta of MF2 a while back where I could have one identity per tab. In the latest version, 2.0.7, this functionality seems gone. I've search extensively, but haven't been able to find anything about this. Could anyone tell me if this functionality has been removed and whether it will return or not?

Thanks.

**Comment by hultmann** [comment]
There are 2 different extensions: Multifox "classic" 2.0.7 and Multifox 2 beta, which is going to be renamed to AllAccounts (that is the one you want). 

Please try the version from this issue: https://github.com/hultmann/multifox/issues/124#issuecomment-30368804
