### ISSUE TITLE
Mutifox and tabs

### ISSUE THREAD

**Issue by anvanlaer** [hultmann/multifox#131]
I would love to use multifox in different tabs instead of different windows.  Is this possible? And how do i do this?

Using version 2.0.7 and firefox 25.0.1

**Comment by AMZMA** [comment]
multifox 2 beta is all you want
http://br.mozdev.org/multifox/all.html#2.0b8

left click on username at url bar, middle click (ctrl + left click) on "Add Account"
login your account

**Comment by anvanlaer** [comment]
I don't know what the problem is but i can't visit that site.  I always get a time-out.

**Comment by hultmann** [comment]
mozdev sites are offline at the moment. You can download from https://github.com/hultmann/allmyaccounts/releases/tag/2.1alpha1 (note it's a completely different extension - uninstall Multifox first)

That being said, it is in my plans for 2014 open new profile in tabs.

**Comment by anvanlaer** [comment]
Thx

**Comment by sttzr** [comment]
this would be great!

**Comment by hultmann** [comment]
Good news, I'm working on it (it is almost usable).

**Comment by Telofy** [comment]
Just curious, when can we expect a new release with this lovely feature?

**Comment by hultmann** [comment]
I expect to have a beta in a week or so.

**Comment by hultmann** [comment]
Please try:
https://github.com/hultmann/multifox/releases/download/2.2.0/multifox-3.0.0b1.xpi

**Comment by Telofy** [comment]
Nice! The menu is too long (when I click the button, the menu reaches down to the bottom of my screen even though it’s mostly empty), but it’s working like a charm! Many thanks!

**Comment by hultmann** [comment]
> The menu is too long (when I click the button, the menu reaches down to the bottom of my screen even though it’s mostly empty)

Good catch, I just fixed it.

**Comment by sttzr** [comment]
Very nice! I use it everyday now!
My special shortcut for new Tab with new identity: CTRL+T + CTRL+ALT+M

**Comment by Telofy** [comment]
I just noticed that when I’m on YouTube and I switch back to by default profile from another one (I’m logged in with both to different accounts), Firefox freezes and starts eating 100% of one of my cores. Can you reproduce that? Should I rather create a separate ticket? Thanks!

**Comment by hultmann** [comment]
> Should I rather create a separate ticket?

Yes, please! I cannot reproduce this bug.

**Comment by hultmann** [comment]
Menu height fixed in 3.0b2: https://addons.mozilla.org/en-US/firefox/addon/multifox/#beta-channel [Development Channel]
