### ISSUE TITLE
Feature request "open (link in) identity profile..."

### ISSUE THREAD

**Issue by andrzej-r** [hultmann/multifox#132]
At the moment there are two ways of opening a profile window:
1.  New Identity Profile
2.  Open Link in New Identity Profile

Both assume the new profile is the one that follow the current one.

The problem:

I have several identity profiles so when I want to open, say, 5th one I have to open 5 windows. Preferably, there should be in option to "open (link in) identity profile..." with a menu showing a list of available profiles + 1. Keyboard shortcuts to first 10 profiles would be handy as well.

**Comment by AMZMA** [comment]
great idea
would be nice if its like this http://puu.sh/61SYw .

and i hope applied to "allmyacc" too.
right click open profile in this tab
middle click open profile in new foreground tab

**Comment by hultmann** [comment]
Fixed in Multifox 3.0 beta. Please try: https://addons.mozilla.org/en-US/firefox/addon/multifox/#beta-channel [Development Channel]
