### ISSUE TITLE
silent failure if unable to contribute via PayPal from Mozilla Add-on page due to X-Frame-Options

### ISSUE THREAD

**Issue by Jskud** [hultmann/multifox#134]
I tried to contribute via PayPal to Multifox from the Mozilla Add-on
page (https://addons.mozilla.org/en-US/firefox/addon/multifox/), but
was unable to do so (because I had 3rd party cookies disabled).  OK,
that's one problem.

But the Multifox page issue is that I got just a blank screen overlay
because of PayPal X-Frame-Options on the response from PayPal --
basically, it looks like the PayPal complaint page is being loading
into some non-PayPal frame, which PayPal's X-Frame-Option forbids.

The complaint in the web console is

```
Load denied by X-Frame-Options:
https://www.paypal.com/us/cgi-bin/webscr?cmd=_dispatch-failed does
not permit cross-origin framing.
```

The Response Headers 

```
X-Frame-Options:    SAMEORIGIN
```

Please consider fixing this, so that others are not presented with a
silent grey overlay if there is a problem trying to donate via PayPal.

Thanks for a great!  add-on.  /Jskud

**Comment by hultmann** [comment]
It seems to be Mozilla bugs. See:

https://bugzilla.mozilla.org/show_bug.cgi?id=823126
https://bugzilla.mozilla.org/show_bug.cgi?id=896653

**Comment by hultmann** [comment]
Closing as it is not specific to Multifox.
