### ISSUE TITLE
Multifox not restoring profiles properly after upgrade to FF27.0

### ISSUE THREAD

**Issue by Komptrman** [hultmann/multifox#136]
Before upgrading to FF 27.0, Multifox 2.0.7 would always reopen (restore) each profile that had been open when it was last closed. After upgrading to FF 27.0, Multifox will now only restore a few of the profiles that had been opened before. Most of the windows now open to the default profile.

Versions Firefox 26.0 & Firefox 27.0 with Multifox 2.0.7.

**Comment by strel** [comment]
Probably mine is the same bug, FF Holly 29.0a1, Multifox 2.0.7, after I accidentally close a window on a secondary profile, I recovered it via History/Recently Closed Windows, and it re-opened on the default profile.

**Comment by Komptrman** [comment]
My Multifox was restoring just fine up until the FF 27.0 upgrade. Then most of the time, the other profiles restore as the default. I have to close them and reopen via the profile selector.

**Comment by hultmann** [comment]
Restoring has always been buggy. It is probably a bug in Firefox session restore.

I'll revisit this when I add support for Multifox tabs.

**Comment by Komptrman** [comment]
This problem is happening to me on two different computers. One of them is running Win7 and Kubuntu, and the other is running WinXP. Both of them have the latest version of Firefox.

Is AllAccounts similar to Multifox? Would it be better for me to use AllAccounts instead of Multifox?

**Comment by hultmann** [comment]
Firefox 28 fails to recover all window profiles, however Firefox 29 Beta seems to work fine 100%! Can someone confirm?

@Komptrman it's personal, you need to try both and choose one (Multifox & AllAccounts are incompatible)

**Comment by hultmann** [comment]
Is this still an issue?

**Comment by Komptrman** [comment]
Yes. It is still acting this way. It will only properly restore one of the other profiles. All other profiles open as the default. It does this on two separate computers. One of them has a virtual desktop in addition to the host desktop, so it is doing this on 3 instances of Firefox. None of them share any code or preferences. One is a dual-core AMD running WinXP and the other is a 6-core AMD Running Linux. I don't recall if it is behaving this way on a third computer. I don't use it very often. I installed Firefox 29 on a Win7 VM and it too only restores one of the profiles upon re-opening.

**Comment by hultmann** [comment]
@Komptrman Is Multifox the only extension enabled?

**Comment by Komptrman** [comment]
Not all of them, but even in the ones where it is the only extension, it is still having the problem. I tried installing FF on one of them and then immediately installing Multifox and testing it, and it will only restore one of the additional profiles. All other windows restore as the default.

**Comment by Komptrman** [comment]
Multifox is still behaving the same way, even after upgrading to FF31.0. It will only restore one additional profile. All others restore to the default, with the tabs that window had open.

I'm using FF31.0, and MF2.2.0, on Linux Kubuntu 64bit (AMD, 6-core) and WinXP32 (AMD, dual-core). It behaves the same way on  both machines. I don't have an Intel machine to test if it is an AMD/Intel related bug. 

A few times, after FF crashed, it actually did restore with all profiles opening up correctly. But this is very rare.

**Comment by hultmann** [comment]
I'm working on per-tab sessions and it uses a different way to restoring profiles. Not sure if it will help fixing this bug, stay tuned for the beta version.

**Comment by hultmann** [comment]
Do you see bug #148 as well? Or are tab titles restored properly?

**Comment by hultmann** [comment]
Multifox 3.0b1 should have this fixed. If not, please reopen this issue.

**Comment by Komptrman** [comment]
My tabs were restoring to the tabs that were open, but the profile for that window was not restoring.
"Do you see bug #148 as well? Or are tab titles restored properly?"

The other person may not have had Firefox preferences set to restore tabs when reopening.

I have FF installed on a Kubuntu Linux machine and it does not restore tabs, even though I have it set to restore tabs in the preferences. I might try to uninstall MF, but I will only do that as a last resort as it can delete my profile cookies.

The FF on my Kubuntu Linux box does not offer the option to restore the last session (it's there in the menu, but not selectable).

**Comment by hultmann** [comment]
Please try:
https://github.com/hultmann/multifox/releases/download/2.2.0/multifox-3.0.0b1.xpi
