### ISSUE TITLE
Feature request: Renaming of default profile

### ISSUE THREAD

**Issue by j-peeters** [hultmann/multifox#137]
Hi I'd love to be able to rename the default profile (in my case with my own nam. It feels clearer to me if all profiles can be renamed to have a specific name. Thanks for considering.

**Comment by JustJilly** [comment]
I agree!

**Comment by hultmann** [comment]
I'll fix it in the next few weeks.

**Comment by j-peeters** [comment]
Brilliant, thanks!

**Comment by hultmann** [comment]
Please try it from https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/
