### ISSUE TITLE
Whitelist domains mode

### ISSUE THREAD

**Issue by MurzNN** [hultmann/multifox#14]
Because sites uses different auth systems and cookie storage, it's too hard to correctly manage all sessions for all sites.
But many users need feature with multi sessions only for short list of sites, for example google.com, yandex.ru, yahoo.com.

So, will be good to add "whitelist domains" mode to enable multifox functional only on specific domains and domain wildcards.  It is not hard, but helps solve auth problems with subdomains. Can you add this mode?

**Comment by hultmann** [comment]
blacklist/whitelist will be the last recourse (when I'm convinced automatic handling is impossible).

**Comment by hultmann** [comment]
You must add a string pref (about:config) with the name:

> extensions.{42f25d10-4944-11e2-96c0-0b6a95a8daf0}.whitelistMode.2.0b7

Enter the allowed top level domains (separated by spaces): "google.com twitter.com facebook.com"

**Comment by Drugoy** [comment]
That's quite an unobvious way, could you, please put that info somewhere into your add-on?

**Comment by MurzNN** [comment]
Thanks for this mode, it solve problems for many sites that is not work with multifox (when domain and subdomain have different auth cookies). 
Will be good to see more friendly interface like configuration window "Exceptions" on Preferences - Content - Block pop-up windows.

**Comment by tbs** [comment]
Why not to use a generic name like extensions.{42f25d10-4944-11e2-96c0-0b6a95a8daf0}.whitelistMode or somethink more obvious with multifox in name? using version number will kill the list in next update. Or I'm wrong?

Anyway, a gui way is a must :+1:

**Comment by Drugoy** [comment]
@hultmann I agree with @tbs that it's better to rename the pref into something like extensions.multifox.domainsignorelist

**Comment by hultmann** [comment]
It is now (2.0b8) 

> extensions.{42f25d10-4944-11e2-96c0-0b6a95a8daf0}.tldWhitelistMode

P.S. I just follow the convention: extensions.[extensionID].prefname

**Comment by zmasterar** [comment]
This is just grat, thanks. But are you thinking on implementing blacklist as well?

**Comment by hultmann** [comment]
No, why do you think it is necessary?

**Comment by hultmann** [comment]
- Go to about:config on url bar.
- Right-click in the window and choose New & String.
- Preference name: extensions.{42f25d10-4944-11e2-96c0-0b6a95a8daf0}.tldWhitelistMode
- For the string value, enter the TLD (top level domain) of your host. E.g. google.com or facebook.com.
- Just google.com, not www.google.com or mail.google.com.
- Do not use quotes. For multiple values, separate them with spaces. E.g. "google.com twitter.com"

**Comment by zmasterar** [comment]
My case scenario is just the opposite of the OP one. I use Multifox in most of the sites i usually visit, but i'm having problems in just few of them. So it's easier for me just blacklist that few ones, instead of adding new whitelisted sites, everytime i visit a new one.

**Comment by Drugoy** [comment]
why {42f25d10-4944-11e2-96c0-0b6a95a8daf0}? that's not readable.

**Comment by hultmann** [comment]
It's the extension ID (defined in install.rdf).

**Comment by MurzNN** [comment]
Other extensions use normal names for settings, for example 
Tree Style Tab: extensions.treestyletab.autoExpand.delay
GreaseMonkey: extensions.greasemonkey.stats.url
Can you look how they do this, and reuse this way?
And will be good to see GUI for switching to whitelist mode and adding sites. Good way will be add "+" button for domains not in whitelist for quickly adding it to whitelist.

**Comment by hultmann** [comment]
Technically I could use whatever name I like. I just follow the convention "extensions.[extensionID].prefname"

BTW, I'm uncertain about the extension name. As Multifox 1 & 2 will coexist, I'll probably have to change Multifox 2 to something else.

**Comment by Drugoy** [comment]
what's the use (for a user, not for a developer) of having 2 coexisting versions of the very same extension?
But even for testing purposes (each add-on has to have it's own settings stored somewhere), it's better to name the prefs "multifox1" and "multifox2" as they will be readable names, so there would be no need for a user to search the matching extensionID.
I hate extensionIDs very much, I think that they have to exist in such a way that a user (even an advanced one who likes to tune about:config prefs) never sees them: they are meant to be for external (machinery) use.

**Comment by Drugoy** [comment]
Please, consider renaming them into human-readable prefs.

**Comment by zmasterar** [comment]
I agree with Drugoy and the others, specially if it's a string u have to enter manually. Besides in that way, if u later wanna search for that string u only have to use the filter, and u don't have to be guessing what's the extensionID.

**Comment by hultmann** [comment]
> what's the use (for a user, not for a developer) of having 2 coexisting versions of the very same extension?

I don't know, but you cannot use 1&2 simultaneously anyway (they are incompatible).

Feedback has shown me 1&2 are different enough to consider them distinct extensions, so Multifox 2 needs a different name. And then I can change the extension ID to human-friendly string.

**Comment by MurzNN** [comment]
hultmann, did you plan to add this into extension settings page instead of manually editing variables?

**Comment by hultmann** [comment]
@MurzNN not in the foreseeable future.
