### ISSUE TITLE
make new multifox version like old version

### ISSUE THREAD

**Issue by elmobiletn** [hultmann/multifox#140]
lik this
http://kaiseg.files.wordpress.com/2009/12/multifox.png
the new version take a long time to navigate between 80 account
i have 80 account and it take a long time to attend the lastest
i hope to have a version 2.0.7 for example like the old style i meen to write the profile number not select it from the list
sorry for my english
thank you a lot

**Comment by hultmann** [comment]
I won't change the current UI.

However, Multifox 2.1.0 (**with Firefox 29 Beta**) makes your interaction less painful, there are scrollbars so it is easier to select the last items.
