### ISSUE TITLE
Show tabs from last time: does not work in non-default profiles

### ISSUE THREAD

**Issue by nicolas-raoul** [hultmann/multifox#142]
Steps to reproduce:
1. Enable "Show tabs from last time" in Firefox preferences
2. Open Firefox (default profile) and open website1
3. Open a new window with profile2 and open website2 inside
4. Close window2
5. Close window1
6. Firefox is now closed, so start it again (default profile). The default profile has remembered website1, which is correct.
7. Open a new window with profile2

Expectation: window2 should have remembered and show website2
Reality: window2 shows `about:startpage`

Thanks for this great tool! :-)

**Comment by hultmann** [comment]
The behavior seems correct. step 7 is not related to session restore. Try Ctrl+Shift+N to reopen website2.

**Comment by hultmann** [comment]
Closing as it is the expected behavior.
