### ISSUE TITLE
Default profile tabs reset to whatever the last closed window was

### ISSUE THREAD

**Issue by nicolas-raoul** [hultmann/multifox#143]
Steps to reproduce:
1. Enable "Show tabs from last time" in Firefox preferences
2. Open Firefox (default profile) and open website1
3. Open a new window with profile2 and open website2 inside
4. Close window1  ←
5. Close window2
6. Firefox is now closed, so start it again (default profile).

Expectation: Should show website1
Reality: Shows window2

This is quite a loss when your default profile has a lot of pinned and opened tabs.

Normal Firefox without Multifox does this too, but Multifox could improve this behavior thanks to its knowledge of profiles. At least the initial window should show the tabs of the last closed default-profile window from last time.

**Comment by hultmann** [comment]
Hmmm, your session contains only window2, this is what Firefox will restore. But now you can restore window1 by pressing ctrl+shift+N.

The current behaviour is what I would expect.

**Comment by hultmann** [comment]
Closing as it is the expected behavior.
