### ISSUE TITLE
Multifox in Firefox 29.x Does Not Work correctly.

### ISSUE THREAD

**Issue by ShelleyJ** [hultmann/multifox#145]
The toolbar button does not open any selections.
![multifox](https://cloud.githubusercontent.com/assets/7309481/2715597/84eabfd8-c511-11e3-8555-df284dce5aa8.jpg)

**Comment by hultmann** [comment]
hmmm... dammit! What is the language of your Firefox?

also, what extensions are you using?

**Comment by hultmann** [comment]
It is possible this could be related to your theme as well.

**Comment by ShelleyJ** [comment]
I am on the Beta Update channel for Firefox, currently at version 29.8. My language is English.

Lists of Extensions and PlugIns are attached.

S.

**Comment by ShelleyJ** [comment]
I do not use a theme in Firefox.

S.

**Comment by hultmann** [comment]
It seems github removes all attachments. Please copy & paste your extensions.

**Comment by ShelleyJ** [comment]
WHAT IS YOUR EMAIL ADDRESS?

My email is: shelley@sjcomm.com.

S.

**Comment by hultmann** [comment]
It seems ReminderFox has issues with Firefox 29. Try moving History or Developer button to toolbar, you'll see the same bug!

**Comment by ShelleyJ** [comment]
Firefox 29 has issues with several extensions.

Do you have access to the Mozilla development team? Maybe you can make them aware of the problems. I have sent them several messages, but I never get any reply.

Thanx for your help. 
Shelley

**Comment by hultmann** [comment]
I believe the right place to report bugs is:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
(Component: Extension Compatibility)

P.S. Multifox will work properly if you move it to toolbar menu/panel.

**Comment by ShelleyJ** [comment]
How can you close a problem when it hasn't been fixed. Workarounds (move to Tools/Menu) are not fixes.

S.

**Comment by hultmann** [comment]
Unfortunately it's not something I could fix. ReminderFox not only breaks Multifox, but also breaks Firefox features.

**Comment by ShelleyJ** [comment]
Yes, those morons make software development into a circus instead of a business.

S.

**Comment by hultmann** [comment]
Please give developers some time. It's hard to keep extensions working :-p

**Comment by ShelleyJ** [comment]
In 20 years of writing code for IBM and other companies (more than 1/2 million lines), I have NEVER had a software bug or a program crash after I released my programs to the user population. I guess I just paid more attention to writing robust code than the morons writing for Mozilla. They release a dozen bugs with every new version.

I have no patience to give these idiots time to fix something that should never have happened in the first place.

S

**Comment by hultmann** [comment]
Sorry, I thought you were talking about extension developers. :smile:

**Comment by ShelleyJ** [comment]
When I find an extension that has functions I like, I download and install it. If it works, then I am happy. If it doesn't work the way I would like it to work, I try to contact the developer and talk about it. Most times, my suggestions are agreeable and sometime down the line, I see that feature appear. (BTW, in a previous lifetime, I have been recognized as an expert in software usability. When I ask for interface changes, I usually know what I am talking about.)

For example: In Multifox, I would like to be able to open my multiple Yahoo accounts in separate tabs instead of in separate windows. Since I notice that you are planning to offer this function in Release 3.0, I have not bothered you with this request. BTW... thank you very much for planning to add this capability.

I have a question:

In a previous message, you said I could recover my Multifox functionality by putting Multifox in the Tools Menu. How do I do this? There don't seem to be any options for where Multifox goes. Thanks again for any information you can give me.

Shelley
