### ISSUE TITLE
2.1alpha2 breaks browser dialogs

### ISSUE THREAD

**Issue by tbs** [hultmann/multifox#146]
This version is semi-broken on current Nightly, it cause error to some Firefox dialogs, example:

![2014-04-21_10-44-55](https://cloud.githubusercontent.com/assets/768954/2754739/7e2c4f56-c95b-11e3-96ec-7cedc899319e.png)

Any chance you fix it soon?

**Comment by tbs** [comment]
hmmm removed this version then installed the AMO one, working fine now.

**Comment by tbs** [comment]
Ahhhhh the AMO version is per window, which I have no interest, then a fix is necessary for "AllAccounts" one.

:(

**Comment by hultmann** [comment]
Crazy bug, even DOM Inspector dialogs are broken and no error messages.

Unfortunately I won't have time in the next weeks.

For now, try accessing directly:
chrome://browser/content/sanitize.xul

**Comment by tbs** [comment]
Right, patience, I will wait for the fix. Few other app are affected by this issue, example [Add to Search Bar](https://addons.mozilla.org/en-US/firefox/addon/add-to-search-bar/).

**Comment by hultmann** [comment]
@tbs do you happen to know when this bug first appeared? (nightly date)

**Comment by tbs** [comment]
11-Apr-2014: http://forums.mozillazine.org/viewtopic.php?f=23&t=2819423

Bad build: http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2014-04-11-03-02-01-mozilla-central/
(BuildID=20140411030201)

Previous one is good (10-04).

**Comment by hultmann** [comment]
I'm 99.9% sure it's a Firefox bug. I'll report it ASAP.

**Comment by hultmann** [comment]
It's https://bugzilla.mozilla.org/show_bug.cgi?id=997636

**Comment by tbs** [comment]
Fix landed, problem solved.

Thanks for your effort.
