### ISSUE TITLE
Disqus comments won't load

### ISSUE THREAD

**Issue by csmalex** [hultmann/multifox#147]
With the Multifox extension enabled (2.1.0), the Disqus comment box fails to load. If I disable the Multifox extension, it works again.

**Comment by hultmann** [comment]
I'll take a look, do you have a URL handy? Did it use to work with a former version?

**Comment by csmalex** [comment]
Example URL: http://www.mywinston-salem.com/small-batch-beer/

I'm not sure it was ever working before, I had just recently started using Multifox.

**Comment by hultmann** [comment]
Could you check with the beta version (Multifox 3.0b2)? It seems to work for me.

https://addons.mozilla.org/en-US/firefox/addon/multifox/#beta-channel [Development Channel]

If you are still able to reproduce the issue can you please reopen this bug.
