### ISSUE TITLE
Tabs no longer show page titles when restarting session

### ISSUE THREAD

**Issue by vcchappell** [hultmann/multifox#148]
This is a new bug, it appeared after upgrading Firefox to version 29.

I have "When Firefox starts: show my windows and tabs from last time" set.

I also have "Don't load tabs until selected" checked.

Before version 29, when I started Firefox I would see all of my windows from my last session, each with the tabs that were open when I closed the session.  Each tab showed the title of the page that it pointed to.  Clicking on any tab would cause the page for that tab to load.  So I could choose in advance whether I wanted to load a particular page on a particular tab, or leave it unloaded until I needed it later.

After upgrading to version 29, when I start Firefox I see all of my windows, with all of my tabs, but the tabs just show "New Tab" instead of the title of the page.  When I click on the tab the page loads, and the title appears.  But I have no way of knowing in advance which page is pointed to by the tab.  The page titles are missing upon startup.

This bug occurs only when Multifox is enabled.  Firefox behaves normally upon startup when Multifox is disabled.

**Comment by vcchappell** [comment]
Further information: windows opened during session restore before the first non-default profile window show the tab titles correctly.  The first window to open during session restore that uses a new identity profile will not show the tab titles.  Windows opened after this during session restore, even using the default profile, will still not show tab titles.

**Comment by vcchappell** [comment]
This bug still exists in Multifox 2.2.0 with Firefox 31.0.

**Comment by hultmann** [comment]
Multifox 3.0b1 should have this fixed. If not, please reopen this issue.

**Comment by hultmann** [comment]
Please try:
https://github.com/hultmann/multifox/releases/download/2.2.0/multifox-3.0.0b1.xpi
