### ISSUE TITLE
All windows reset to default profile on quit since FF29

### ISSUE THREAD

**Issue by tdubourg** [hultmann/multifox#149]
Since I upgrade to Firefox 29, Multifox sessions do not survive a Firefox restart.

I always quit firefox by the "Quit" button (or its shortcut CTRL + SHIFT + Q on my firefox).

But since Firefox 29, when I quit Firefox, and then restart it, all windows get back to the "default profile". This makes Multifox pretty much unusable to me. I am ending up with 6 windows because I have to reopen new windows to get my profiles back... 

Any thoughts on what could cause the bug? I have seen it happened before, at least one issue was opened about that but nothing really followed...

I will provide debug information on request, if I'm explained how to provide it :)

**Comment by hultmann** [comment]
Is this bug same bug as #136?

**Comment by tdubourg** [comment]
Not exactly. #136 says a few profiles would be restored while in my case, no profile are restored (everything is just moved to the default profile).

Thanks.

**Comment by hultmann** [comment]
Multifox 3.0b1 should have this fixed. If not, please reopen this issue.

**Comment by tdubourg** [comment]
When will 3.0b1 be pushed to the Mozilla addons website?

Thanks!

**Comment by hultmann** [comment]
Not sure, but I'll post a link here for testing.

**Comment by hultmann** [comment]
Please try:
https://github.com/hultmann/multifox/releases/download/2.2.0/multifox-3.0.0b1.xpi

**Comment by tdubourg** [comment]
"Could not be installed because it is not compatible with Firefox 29.0.1" ...
