### ISSUE TITLE
not saving cookies

### ISSUE THREAD

**Issue by peekaa** [hultmann/multifox#151]
IN new Identity profiles Windows multifox stop saving cookies. At www.google.com I have to see all the time if I want to set google default, if I agree with cookies, and if I would like to have chrome. Its annoying. Thank you. I think that before ff30 it works well.

ff30, multifox 2.2.0

**Comment by peekaa** [comment]
2.1 works fine

**Comment by peekaa** [comment]
well I found the solution. In previous version I use all the time option "New". And the new was in the meaning of "next one, if that exists", so after default profile "profile 1" was chosen. Now, after "new" is really always new one, not the Profile 1, that was created sometimes before. Now I have to choose the already existing profiles if all my previous credential should be used.

**Comment by hultmann** [comment]
Closing as it is the expected behavior.
