### ISSUE TITLE
 View all open at the same identity.

### ISSUE THREAD

**Issue by Michaelax** [hultmann/multifox#154]
You can display all open tabs as does the add-on "Tile Tabs" https://addons.mozilla.org/it/firefox/addon/tile-tabs/?
If you open many "New identity profile", you have to check them one at a time and this is inconvenient.
It would be very useful to be able to simultaneously display all open windows.
===========================================================00

Original message:
É possibile visualizzare contemporaneamente tutte le schede aperte come  fa l'add-on "Tile Tabs" https://addons.mozilla.org/it/firefox/addon/tile-tabs/ ?
Se si aprono molti "New identity profile", bisogna controllarle una alla volta e questo è scomodo.
Sarebbe molto utile poter visualizzare contemporaneamente tutte le finestre aperte.

**Comment by hultmann** [comment]
Do you need thumbnails or a list is enough?

**Comment by Michaelax** [comment]
# The best thing would be able to view all open identity on screen together (like tile tabs). In this way, you can follow many things at once.

ORIGINAL MESSAGE
La cosa migliore sarebbe poter visualizzare tutte le identitá aperte sullo schermo insieme (come fa tile tabs).  In questo modo si possono seguire più cose contemporaneamente.

**Comment by Michaelax** [comment]
I apologize for the size of the font of the previous message, but I do not know how to shrink it.
With regard to the request, can you get?

# 

ORIGINAL MESSAGE

Chiedo scusa per la dimensione del font del messaggio precedente, ma non so come rimpicciolirlo.
Per quanto riguarda la richiesta, si può ottenere?

**Comment by hultmann** [comment]
I'm sorry but this is not going to be implemented because it needs too much work to get it working properly.

**Comment by hultmann** [comment]
BTW, Multifox 3.0 beta supports per-tab profiles, not sure if it will make difference to your workflow.

https://addons.mozilla.org/en-US/firefox/addon/multifox/#beta-channel [Development Channel]
