### ISSUE TITLE
google drive

### ISSUE THREAD

**Issue by peekaa** [hultmann/multifox#155]
google drive is not working in another profile :-(  , see http://i.imgur.com/2GshYgr.png

xpsp3, ff30, mf 2.2

**Comment by hultmann** [comment]
Seems to work for me. What kind of file are you trying to view?

Please try to open gdrive in a private window, you should get the same result...

**Comment by peekaa** [comment]
it works with the old one gdrive, but not with the new one http://googledrive.blogspot.cz/2014/06/meet-new-google-drive_25.html. In default profile and in private, too, all works fine.

**Comment by hultmann** [comment]
Thanks, I can reproduce the bug now.

**Comment by hultmann** [comment]
Fixed in 3.0b2: https://addons.mozilla.org/en-US/firefox/addon/multifox/#beta-channel [Development Channel]
