### ISSUE TITLE
T

### ISSUE THREAD

**Issue by ShelleyJ** [hultmann/multifox#156]

**Comment by hultmann** [comment]
closing empty issue.

**Comment by ShelleyJ** [comment]
I have described this issue at least three times.

The Multifox dropdown menu in Firefox (version 29.0 and above) is empty. There are no firefox windows listed.

Picture is attached.

Shelley

On Thursday, July 24, 2014 9:13 PM, Jeferson Hultmann notifications@github.com wrote:

Closed #156.

**Comment by ShelleyJ** [comment]
Firefox on my laptop (Firefox v30.0) works just fine.

Please tell me how I can delete Multifox from my desktop and re-install a complete NEW version.

Thank you,
Shelley

On Thursday, July 24, 2014 9:14 PM, Jeferson Hultmann notifications@github.com wrote:

closing empty issue.
