### ISSUE TITLE
Toolbar menu doesn't work.

### ISSUE THREAD

**Issue by ShelleyJ** [hultmann/multifox#157]
I am using Firefox 31.0. The toolbar menu is almost completely empty (see attachment).

I have tried to re-install Multifox, but it doesn't change anything.

Thanks for your help.

Shelley
shelley@sjcomm.com
![multifox](https://cloud.githubusercontent.com/assets/7309481/3668068/25093410-1213-11e4-8784-a8b02c4470cb.jpg)

**Comment by hultmann** [comment]
Issue #145?
