### ISSUE TITLE
Multifox in Firefox 29.x Does Not Work correctly.

### ISSUE THREAD

**Issue by ShelleyJ** [hultmann/multifox#158]
I have described this issue at least three times.

The Multifox dropdown menu in the Firefox toolbar is empty!!! 

I have attached a picture of this issue.
![multifox](https://cloud.githubusercontent.com/assets/7309481/3697850/8307b10e-13b2-11e4-9b3a-56f7a354eafd.jpg)

**Comment by hultmann** [comment]
Did you report it to ReminderFox authors? Like I mentioned in #145, there is nothing I can fix here.

https://github.com/hultmann/multifox/issues/145#issuecomment-40672572

**Comment by ShelleyJ** [comment]
What are you talking about? ReminderFox works perfectly. THIS IS ABOUT MULTIFOX.

Tell me how I can remove MultiFox and install a brand new copy. I have tried to "Remove" in the AddOn controls of Firefox, but it installs the same copy without cleaning it up.

MultiFox works just fine on my laptop in Firefox v30.0. What can **\* I **\* do to fix this problem?

Shelley

On Thursday, July 24, 2014 9:40 PM, Jeferson Hultmann notifications@github.com wrote:

Did you report it to ReminderFox authors? Like I mentioned in #145, there is nothing I can fix here.
#145 (comment)
