### ISSUE TITLE
Full CPU Usage when Switching Back to Default Profile on YouTube

### ISSUE THREAD

**Issue by Telofy** [hultmann/multifox#159]
I’m using the beta version multifox-3.0.0b1.xpi. When I visit the YouTube homepage (or any YouTube page) with an auxiliary profile and switch back to the default profile, my browser freezes using up 100% of one core (plus a little of the other). I can then terminate Firefox with signal 15.

Switching between auxiliary profiles works, and switching from the default profile to an auxiliary profile works as well. I’m logged in to different YouTube accounts with each of these profiles.

Unfortunately I’ve already heard that it’s not trivial to reproduce, so if I can help with any more information, please ask.

Many thanks for the lovely add-on!

**Comment by Telofy** [comment]
Wow, thanks! That was fast. :-D

**Comment by hultmann** [comment]
Fixed in 3.0b2: https://addons.mozilla.org/en-US/firefox/addon/multifox/#beta-channel [Development Channel]
