### ISSUE TITLE
v2.0b2 Limited profiles number(15)

### ISSUE THREAD

**Issue by Zalov** [hultmann/multifox#16]
When i log in in more than 15 yahoo answers account the others accounts disappear exactly when i log in a new one, i read about problem #7 and it is not the same i think because i had those 15 accounts open for about 3 hours  and they were ok and they didnt disappear or log me out but when i log in more than 15 they instantly dissapear if i do. even if i log in 3 accounts in 2 minutes.

somehow it is limited problem appears when i try to log in in more than 15 yahoo answer accounts. Thanks.

When i log on new account and they are 15 the old one instantly dissapear.

**Comment by hultmann** [comment]
Maybe the menu only shows the first 15 items, it would be easy to fix.

**Comment by hultmann** [comment]
Nope, a menu can show infinite items.

**Comment by Zalov** [comment]
It is wierd now i can make 18 accounts but same happens if i make 1 more than 18 the last one dissapears so every new account replaces the last one now limit is set to 18               =S

**Comment by Zalov** [comment]
it is strange i had 18 but accounts but they dissapeared and now they are 15 again,i think cookies expired fast or something else this bug is wierd please fix it.

**Comment by Zalov** [comment]
now i have only 13 accounts like it disappear over time

**Comment by Zalov** [comment]
now i have 12 accounts maybe is a cookies problem

**Comment by hultmann** [comment]
Let's see! I'm investigating the cookie issue right now.

**Comment by Zalov** [comment]
if you want i can make a video showing you the problem, just ask and i will do it and post it on youtube.

**Comment by tbs** [comment]
I have same problem, account are gone as magic.

ps: you have any eta for 2.0b3?

**Comment by hultmann** [comment]
ETA = as soon as I fix some bugs. :)

**Comment by Zalov** [comment]
evil bugs!! they enjoy sabotaging your work  >:(

you must exterminate those lil basterds xD

**Comment by ManAtWork** [comment]
I encountered similar issue several times, when I have 11 accounts in one site I created within minutes. 6 of them disappeared in next day and I need to re-create the accounts again.

**Comment by hultmann** [comment]
OK, I've finally found out what's going on here. Multifox 2 quickly reaches a Firefox limit (cookies per host). Then, old Multifox cookies are automatically removed by Firefox to make room for the new ones.

I'll have to change the cookie naming scheme to fix this.

**Comment by hultmann** [comment]
It seems this bug is fixed. I'm now fixing the regressions. :)

**Comment by hultmann** [comment]
This was fixed in 2.0b3. Please let me know if there is still an issue.
