### ISSUE TITLE
Right click on tabs to quickly change profile

### ISSUE THREAD

**Issue by ooker777** [hultmann/multifox#165]
Multifox is an add-on I'm looking for. It's great. I have this suggestion: right click on tabs to quickly change profile. For example, I use two Facebook account. Sometime I have a website I want to share on account A, but the profile I'm in is account B, which I don't want to. Instead of copy the link of the site, switch to profile B, open Facebook and paste it on status, I can easily right click to the tab and that site is on the other profile, then I can click the share button integrated in that site.

**Comment by ciuly** [comment]
You can click on the multifox icon in the toolbar and select another profile. The current page will then refresh in that profile. Is that not what you want?

**Comment by ooker777** [comment]
Now I have managed to do that. Thank you.
