### ISSUE TITLE
How to keep Tabs Group after restarting Firefox when using Multifox?

### ISSUE THREAD

**Issue by ooker777** [hultmann/multifox#166]
I'm use Tabs Group occasionally. However, when I restart Firefox, all of the tabs are gone, except the last group I use. Is it possible to keep them? Thank you.

**Comment by hultmann** [comment]
It is supposed to be fixed in Multifox 3.0.0b3. Please try it and reopen this issue if that doesn't work.

https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by ooker777** [comment]
I have made a quick test, it does well. I'm not sure that this will work if I use many tab groups and each group has many tabs inside. Thank you so much.
