### ISSUE TITLE
Mutifox 3.0.0b1 and Google drive

### ISSUE THREAD

**Issue by anvanlaer** [hultmann/multifox#168]
Since a couple days i can't open my Google drive in another profile then my default profile.  I've attached a screenshot.

![2014-10-31 14_00_12-mijn schijf - google drive](https://cloud.githubusercontent.com/assets/4437672/4860955/e9b110d8-60fd-11e4-9b77-d154f1b88752.png)

Can this get solved?

**Comment by hultmann** [comment]
Fixed by #155. The latest version is 3.0.0b4

**Comment by hultmann** [comment]
BTW, Multifox should be automatically updated, for some reason it didn't work...

**Comment by anvanlaer** [comment]
Well it didn't automatically get updated. I updated it manually and this is solved. But now i have a new problem. I'll make an new thread.
