### ISSUE TITLE
Multifox 3.0.0b4 and name of the profile

### ISSUE THREAD

**Issue by anvanlaer** [hultmann/multifox#169]
Ive updated to multifoc 3.0.0b4 and now the names of my profiles change back to the number when i change profiles.  I like to give the profiles the name of the e-mailadres i use for that profile and now i only have 2 - 3 - etc.

**Comment by hultmann** [comment]
Good catch. I'm going to fix that.

**Comment by ciuly** [comment]
any idea when this fix comes in? to note that in one of my pinned tabs, beside the change to the number, it also changed profiles. Gmail was logged on and I just got a message that I've been signed out, noticed then that the profile has changed.

**Comment by hultmann** [comment]
Friday or Saturday. (for the signed out bug, please file a new issue)

**Comment by hultmann** [comment]
Fix available (b5): https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/
