### ISSUE TITLE
Pinned tab switched profiles and name

### ISSUE THREAD

**Issue by ciuly** [hultmann/multifox#172]
in one of my pinned tabs, beside the change of name to the number, it also changed profiles. Gmail was logged on and I just got a message that I've been signed out, noticed then that the profile has changed.
May be related to  #169
(in b4)

**Comment by hultmann** [comment]
@ciuly is it different from bug #164?

**Comment by ciuly** [comment]
yes. The identity switch happened while the browser was already running for many hours. 164 happens at startup (haven't tested that in a while as I try to keep my tabs properly identified). Now (since that report) I also have many unpinned tabs with different identities, in case it counts.

This particular issue only happened once, for one pinned tab only, so far. The name change (169) happens almost daily, was not able to find a pattern for it.

**Comment by ciuly** [comment]
as an update: lately (as of latest dev build (at least)) I keep noticing, almost on a daily basis, that multifox somehow "crashes" or something. The effect is that the pinned non-default tabs turn to default profile, gmail obviously signs out, and when clicking on the multifox button, when the list of profile and menu buttons appear, now appears nothing (there is a start of a menu drawn, but it's completely empty, so the click goes through). (I didn't have non-pinned non-default profile tabs. Will try to keep a few open)
After a minute or so, the multifox profile gets back to it's sane self with proper menu items.
After getting this a few times, I also get an error from Session Manager add-on, saying "undefined" in a few places and informing me that it cannot save backup session. This usually ends with an immediate crash of FF when the 2 events happen together or shortly one after the other.
What I did notice was that FF eats up quite some memory (2 to 3 GB, summed RAM and swap) (this is on a WinXP x32). Also, I have configured FF to release RAM when minimized, although I cannpt say that this ever happened while FF was minimized or shortly after restored. But this did happen while FF was left alone and not touched for extended period of time, while I was working on something else.

**Comment by ciuly** [comment]
I'm pretty sure, as explained in #164 that this is caused by the same memory problems. And I'm also pretty sure these memory related crashes of FF (which indeed happen like 3-4 hours of not doing anything in FF, out of the sudden, are caused by FF itself (most likely a bug, I'd guess a leak of some sort in JS).
anyway, I'll close this on same considerations.
