### ISSUE TITLE
All tabs with all identities lost their cookies or soemthing

### ISSUE THREAD

**Issue by ciuly** [hultmann/multifox#174]
This is a weird one. I installed b5 about 2 days ago. So it went one day with no issues, survived a restart, another day and then I closed FF. This morning when I started FF, all tabs were logged out of everything, no matter the profile.
I think FF did an update yesterday? I know it popped up a new tab with some firefox OS stuff I was not interested in. Other than that, everything was normal.
Will see tomorrow if it looses logins again or not.

**Comment by ciuly** [comment]
all good this morning. Will keep it open for a few more days. If nothing bad happens, I'll close this as being a one time glitch.

**Comment by ciuly** [comment]
never happened again since.

**Comment by ciuly** [comment]
Just happened again now. I closed FF, and minutes later I remembered I had to do something so I started it back again. None of the tabs had their stuff logged in. This is with b6 now running for quite some time with no other issues.

**Comment by ciuly** [comment]
the same thing happened now with a system crash. Session Manager addon restored the tabs and all, identities were restored, but cookies and that sort of information not.

**Comment by hultmann** [comment]
My guess it is an extension incompatibility issue.

A similar issue (fixed in 2.2.1) had several reporters, but I finally managed to fix it (apparently it was a Firefox bug).

**Comment by ciuly** [comment]
I'm on 3b6 so I would assume that fix is there.
But given the fact that the tabs are restored with proper identities, doesn't that mean that the cookies&co data loss is more of a multifox issue? Back before MF, when only FF and session manager were handling tabs and cookies and what not, there were no problems with cookie loss, ever. Crashes, slow shutdowns, task kill, etc. This only became a problem with the beta version of MF.

If you have some logging around the saving of cookies and session data, I'd be happy to provide them whenever this happens again.

**Comment by hultmann** [comment]
If you start Firefox with `firefox.exe -console` (Windows), an error message from Multifox may appear there or, in the Error Console/Browser Console.

Firefox has a cookie log feature, I don't know if it would help
https://developer.mozilla.org/en-US/docs/Creating_a_Cookie_Log

**Comment by ciuly** [comment]
I don't think the browser console is helpful here, but when it will happens again, I'll try to  check it, just in case. Maybe this vacation I'll have some time to troubleshoot this.

**Comment by ciuly** [comment]
this hasn't happened since then so I'm closing it.
