### ISSUE TITLE
Javascript-rich webapps fail with Firefox 34

### ISSUE THREAD

**Issue by imtayadeway** [hultmann/multifox#176]
I just upgraded to Firefox 34, and webapps such as Trello and Jira have become unresponsive. All other plugins have been disabled, and the issue persists. They do however work if I open them in a private window.

Here's an example of the output from the console:

```
Error: Permission denied to access property 'toString'
Error: Permission denied to access property 'message'
uncaught exception: unknown (can't convert to string)
```

**Comment by hultmann** [comment]
Did you try it with Multifox 3? https://getmultifox.com/

**Comment by imtayadeway** [comment]
My apologies! I did not realize this was publicly available yet. This does indeed address the issue. Many thanks!

**Comment by hultmann** [comment]
Great! Hope Mozilla gets it approved soon.
