### ISSUE TITLE
Cannot use persona.org with profiles but the default

### ISSUE THREAD

**Issue by dorfsmay** [hultmann/multifox#177]
## How to re-create the problem
1. - with Multifox, use any profile but default
   - go to https://login.persona.org
     With other browsers and the default profile you will see a "Sign in" button at the top right hand corner, but won't be able to see it when using other profiles in Multifox.
2. - with Multifox, use any profile but default
   - go to https://developer.mozilla.org/Persona
   - click on "Sign in with", and select "Persona"
     It will open a new window, but instead of a login menu you will get the error message "We are sorry, but currently your browser is not supported."

**Comment by hultmann** [comment]
Are you using Multifox 3.0? I see the"Sign in" button. (Multifox 2.x has known issues with Firefox 34)

**Comment by dorfsmay** [comment]
I upgraded to 3.0 it solved it.

**Comment by hultmann** [comment]
Great! Hope Mozilla gets Multifox 3.0 approved soon.
