### ISSUE TITLE
Additional Profiles do not load Game. Only default works.

### ISSUE THREAD

**Issue by ststreck** [hultmann/multifox#178]
I'm playing http://lordsandknights.com and use Multifox to open several accounts in parallel windows. 
Since the last Firefox Version the game only loads in the Default profile. 
All addtional Multfox profiles get stuck while loading. 

I deinstalled Firefox completely and reinstalled everything, but same effect. 

Hope this can be fixed soon. 
Thanks.

**Comment by hultmann** [comment]
Are you using Multifox 3.0? Multifox 2.x has known issues with Firefox 34.

**Comment by ststreck** [comment]
As I couldn't find multifox in the Add-ons in Firefox I use 2.xx
I upgraded to 3.x and now it works 
Thanks.

**Comment by hultmann** [comment]
Great, Hope Mozilla gets Multifox 3 approved soon.
