### ISSUE TITLE
Cannot allow third-party cookies / weird option overriding

### ISSUE THREAD

**Issue by cw337** [hultmann/multifox#18]
Go to Options > Privacy > Custom settings for history, selecting "Accept cookies" will be deselected within a second... so does this mean there is no way to allow third-party cookies while using Multifox?

**Comment by hultmann** [comment]
If you change the settings, close pref window, browse some pages, open the pref window, the settings won't be as you selected?

Multifox actually changes the settings for a few milliseconds, but they should be restored!

**Comment by cw337** [comment]
I couldn't change the settings, because the selection changes too fast... I achieved it by disabling the extension, restarting Firefox, setting it, re-enabling and restarting...
