### ISSUE TITLE
Open new tab in the same profile as the current tab

### ISSUE THREAD

**Issue by dorfsmay** [hultmann/multifox#183]
New tabs (ctrl-T) always open with the default profile. I typically want to open a new tab in the same profile as the current tab. This is the way it used to work when profiles were per window, and is very convenient. Even if it were a new button or a new key combination, I can learn that, but right now from what I can tell, there is no way to do this.

**Comment by hultmann** [comment]
What about "Window Mode" in Multifox 3.1 beta?

https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by dorfsmay** [comment]
That's great to have the choice between the old and new behaviour. This will probably be sufficient, although I liked the idea of a new tab in the same profile as the current one.

**Comment by hposca** [comment]
Hi @hultmann , it is me again.
I'd say this behavior is really a bit annoying, and it is still happening with 3.1.0b2.

**Comment by Brilleaux01** [comment]
@hposca did u go to 3.1.0b2 options and tick the box saying 'window mode' it will open new windows ok of each account

**Comment by hposca** [comment]
Hi @Brilleaux01 , unfortunately for me it doesn't work as you said.
I even described what I have to do to achieve the old behavior [here](https://github.com/hultmann/multifox/issues/185).

**Comment by hultmann** [comment]
Fixed by 3.1b3 + Window Mode.
