### ISSUE TITLE
Clear All

### ISSUE THREAD

**Issue by FalseFerret** [hultmann/multifox#184]
I use this extension and my browser in a temporary way, where I want everything to be reset to a clean state each time I restart firefox.
Could you add in a clear all on restart option?
I think the cookies are all cleared by firefox settings, but the profiles and their windows remain behind.
I added this line into Bootstrap.extensionStartup()
while (ProfileAlias.getRegisteredProfiles().length) ProfileAlias.remove(ProfileAlias.getRegisteredProfiles()[0]);
That seems to do what I want, though it may be leaving behind some stuff I don't know about.
Great extension, thanks.

**Comment by hultmann** [comment]
Hello,

What privacy options do you use in Firefox? clear browsing data?

**Comment by FalseFerret** [comment]
Hey, 
custom settings, clear history on close.

**Comment by hultmann** [comment]
Only history, not cookies? Currently my patch automatically remove profiles when clear cookies is checked.
