### ISSUE TITLE
multifox 3 (in FF 34.0) stopped opening new windows on switching profiles

### ISSUE THREAD

**Issue by nekromoff** [hultmann/multifox#186]
you have apparently changed functionality / UX and now clicking the profile does not open the new window for that profile, but user has to  manually create new window and then click the profile.

i would say this is a bug, not a feature as it requires further activity from user instead of simple new window opened with the profile selected.

**Comment by ACGicomer** [comment]
Echoing nekromoff's comment. Multifox no longer opens a new window per profile. It seems this was an (in)direct result of the ability to have per-tab profiles. In addition, switching between profiles no longer switches to an open window (or tab) that is set the desired profile.

While I can see the merit in either option, I think it would be better to have the option to use either per-tab or per-window profiles. 

For development work I find it more helpful to have each window to be a separate profile with the same web application sessions in each window. It is very common for me to work with several tabs in multiple profiles allowing me to keep projects that I'm working on separate.

**Comment by nekromoff** [comment]
> It is very common for me to work with several tabs in multiple profiles allowing me to keep projects that I'm working on separate.

Exactly! For example different sessions/windows with Google Analytics, Webmaster Tools etc. tabs open. This does not combine well with the (per profile) tabs. Actually, it confuses hell of a lot users as it is highly discouraged to change basic behavior of the apps from version to version.

**Comment by nekromoff** [comment]
aha!
it has been fixed here:
https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/?page=1#version-3.1.0b2
(change preferences setting to emulate window mode)

**Comment by ACGicomer** [comment]
I just found the same thing thanks
