### ISSUE TITLE
New tabs problem

### ISSUE THREAD

**Issue by ghost** [hultmann/multifox#187]
I use Multifox from a year and it always worked fine, but now it's acting in a strange way.
In the past, if I tried to open a new identity profile, it was opened in another window, as logic says.
Now, if I switch to a id profile to another, this doesn't happen. 
This is real awful, Multifox it's useless for me since this happens. 
How can I fix it?
Let me explain better: I open Firefox, I switch to tab 2, but the window is always the same, the current page is reloading.

**Comment by hultmann** [comment]
Hello,

Please try 3.1 beta, select "Window Mode" and let me know if it work properly. :)
https://addons.mozilla.org/firefox/addon/multifox/versions/

BTW, why per-tab profiles are not useful for you? You can open the current page in another tab by selecting the profile with a middle click or ctrl+click.
