### ISSUE TITLE
Profile problems

### ISSUE THREAD

**Issue by Grumpface** [hultmann/multifox#188]
In the past, a new window with the selected profile would open when I use Multifox. But very recently when I would select a new profile it would do absolutely nothing and now I'm back to using multiple browsers to simulate what I would do if Multifox is working properly. How do I fix this?

**Comment by hultmann** [comment]
Hello,

Please try 3.1 beta, select "Window Mode" and let me know if it work properly. :)
https://addons.mozilla.org/firefox/addon/multifox/versions/

BTW, why per-tab profiles are not useful for you?
