### ISSUE TITLE
[MF 2 beta 2] Identity disappearing randomly.

### ISSUE THREAD

**Issue by FallMonkey** [hultmann/multifox#19]
As title, I just installed mf 2 beta 2 for the ease of swapping cookies.

However, as I keep logging in and out to create new identity files, sometimes the previous created identity files will disappear from the dropmenu where I wish to choose from for certain cookie.

Only when I create no more than 3 idenities, will there be no such issue. Once I created more than that, the issue will occur to random idenity file( the one I created before 3 idenitites, or the one I created after 3 idenitites, totally unpredictable)

Any idea on that, or the fix for that? Since cookieswap is not supported for a while, this's the last hope i could tend to for the sake of my browsing need.

Thank you very much.

**Comment by hultmann** [comment]
Thanks for the report. There are other bugs about this issue, like #16.

(I suggest you to use Multifox 1.3, which doesn't appear to have this bug.)
