### ISSUE TITLE
Unable to use anymore 

### ISSUE THREAD

**Issue by arowdy1** [hultmann/multifox#192]
Unable to use anymore ,multifox only tries to switch the window/tab I have open. I have tried opening a new window/tab first but does not work.On facebook I get a message "Sorry, we got confused:
Please try refreshing the page or closing and re-opening your browser window."  which is equal to signing out and logging in on a different account.I use Firefox 34.0.5 I tried another older ver of multi but it did the same thing.Any suggestions? Thanks

**Comment by Komptrman** [comment]
You will get this message when a page reloads and the address has some sort of messageID or another number belonging to somebody else's account (i.e. another profile). Try using the Firefox menu on the far right (the three bars) to open a new window. The new function of Multifox will change the profile in the current tab, rather than open a new tab or new window.

**Comment by hultmann** [comment]
@arowdy1 What version of Multifox are you using?

**Comment by arowdy1** [comment]
I tried several right now I have 3.1.0b3.  I am able to use this 1 if  I open a window first. then ask for a new profile. I uninstalled and tried  allaccounts and older multifox's. This one seemed to work the best for me .Thanks a bunch !

**Comment by hultmann** [comment]
3.1b3 works fine for me, no issues with 2 facebooks.

Anyone else having this bug?

**Comment by acatlover8** [comment]
I am still unable to use it.  Very sad because I really, really like it.  I am on version 3.1.0 and it says my version is up to date.  How do I find the newer one?

**Comment by hultmann** [comment]
Unfortunately this bug will remain unfixed until I have a way to reproduce it on my computer.

**Comment by acatlover8** [comment]
I don't know if it helps, but I am using Windows 7 and Facebook.  It was working and then one day it wasn't.  I don't know if it was an  update on Firefox or Windows or what that kicked it in.  Is there an older version I could try to see if it fixes the problem?

**Comment by hultmann** [comment]
@acatlover8 Try 3.0.0 and let us know what happens. https://addons.mozilla.org/firefox/addon/multifox/versions/

**Comment by acatlover8** [comment]
Hi there,

Unfortunately, I am still getting the same problem.  I use multifox for facebook accounts.  I have  background in software testing so I hope this can help you.    

 

1.  I log in to my default profile.

2.  I then select “new” profile

3.  Here’s where it’s different from before:  When the new window comes up, I get this:



In the past, when the second window popped up, on the tray at the bottom would be a second FF icon.  It was easy to go between the two profiles by clicking on the appropriate icon.  Now, it doesn’t do that, just the one is visible as you can see in the picture

4.When I click on the login button, it does go to the login screen.  I then log in to profile #2.

5. So, now I want to go back to profile #1.  The only way to access it is from the drop down menu.  I have to go there and select “default profile”.  It will go  back to the default profile.  However, when I then go back to the  drop down menu to go to profile #2, this happens:  (it was so much easier to just click on the icon at the bottom of the screen.) 

 



 

6.  At this point, when I click on the “close” button, I’m still on profile #1, even though I had selected profile #2.  Also, although I’m still logged in to profile one, it won’t work, it just hangs up and the browser stops responding.  

 

Anyway, I don’t know if this will help you at all, but wanted to give you my experience.  Thanks so much for providing this add on, I used it for a long time and absolutely loved it!  

 

Cindy Green

**Comment by hultmann** [comment]
Cindy, it seems Github ate your image attachments (see https://github.com/hultmann/multifox/issues/192#issuecomment-74461925)

According to https://github.com/hultmann/multifox/issues/192#issuecomment-69416011, reverting back to an older version works fine again (I don't know which one of them).

**Comment by acatlover8** [comment]
Thanks!  I'll play around with maybe an older version of Firefox or different multi-fox versions.  Thank!

**Comment by acatlover8** [comment]
Ohhhh, cracked the code!  Doh!  I finally see the comment on the list of versions that says if you want to "Go to Add-ons / Extensions / Multifox / Options, enable Window mode preference."  That's what makes it work on Windows 7.  The new profile has to be opened in a new Window!  Once I checked that box, it worked fine.

**Comment by arowdy1** [comment]
I am still using the 3.1.0 , since I checked   the box I have not had any issues with it ! Thanks a bunch!!

**Comment by nunpiyu** [comment]
Have this issue too
Work fine until the 5th profile tab. Can not log in again just like before
