### ISSUE TITLE
profiles deleted after Firefox restart

### ISSUE THREAD

**Issue by dorfsmay** [hultmann/multifox#193]
I set my browser to delete everything when I quit Firefox (cookies, history, etc...). This was never an issue with MultiFox in the past, but now (since 3.1.0 possibly), when I re-start Firefox, all my profiles are deleted.

**Comment by hultmann** [comment]
It's #184. Until 2.x, Multifox removed profiles when cookies are removed.

**Comment by dorfsmay** [comment]
So the bug came back in 3.1.0?

**Comment by hultmann** [comment]
It was buggy in 2.x/3.0, 3.1 fixed it.

**Comment by dorfsmay** [comment]
So the desired state is that deleting cookies deletes all profiles?

If so, could we add an option in security to enable deleting cookies without the profiles?

**Comment by hultmann** [comment]
An  additional option in "clear when restart" dialog would be the best fix.

Meanwhile, you can avoid the behavior removing this line:

https://github.com/hultmann/multifox/blob/ce79a23b64c4a4bb339e4a045c6af8e00d97c172/src/modules/new-window.js#L35

**Comment by dorfsmay** [comment]
How difficult would it be to implement such an option?

**Comment by hultmann** [comment]
Adding it multifox/options.xul would be straightforward.
Adding it to Firefox prefs would be the best choice but very difficult, since Firefox prefs are moving to a tab.
