### ISSUE TITLE
Multifox blocks the login if the domain name of the sito has only one level

### ISSUE THREAD

**Issue by realefab** [hultmann/multifox#2]
After installing multifox I can not login anymore in my intranet server using its hostname (http://myserver/). I had to add extension (http://myserver.network/).
Otherwise I got this error:
Error: [Exception... "Component returned failure code: 0x804b0050 (NS_ERROR_INSUFFICIENT_DOMAIN_LEVELS) [nsIEffectiveTLDService.getBaseDomain]"  nsresult: "0x804b0050 (NS_ERROR_INSUFFICIENT_DOMAIN_LEVELS)"  location: "JS frame :: resource://multifox-modules/main.js :: <TOP_LEVEL> :: line 1632"  data: no]
Source File: resource://multifox-modules/main.js
Line: 1632

**Comment by hultmann** [comment]
Thanks, this is going to be fixed in beta 2.

**Comment by hultmann** [comment]
This is fixed in Multifox 2 beta 2. Let me know if problem still persist.

**Comment by realefab** [comment]
I confirm that the bug is fixed.
Thank you for your nice extension.
