### ISSUE TITLE
[BUG] Firefox 37 brokde multifox windows mode

### ISSUE THREAD

**Issue by dorfsmay** [hultmann/multifox#203]
With firefox 37, multifox 3.1.0.0 no longer works correctly in windows mode:
- open firefox: get a default profile window - GOOD
- create new profile: open a new window in profile 2 - GOOD
- click on + sign to get a new tab: open a new tab in profile 2 - GOOD
- click on + sign again for new tab: open a new tab in DEFAULT profile - BAD
- try to switch profile back to profile 2: open yet a new window - ???
- try to merge that window in the second one: merges, but switch that window to default profile - BAD

This makes multifox completely unusable on that version of firefox.

**Comment by hultmann** [comment]
tab for browser not found @
https://github.com/hultmann/multifox/blob/12508b86fc009f42f7cb385fb26a749a71ea9e06/src/modules/new-window.js#L351

It works properly when browser.newtab.url != about:newtab. So I believe it's related to a about:newtab optimization.

**Comment by hultmann** [comment]
Yes: https://bugzilla.mozilla.org/show_bug.cgi?id=1077652

**Comment by hultmann** [comment]
A fix is on the way.

**Comment by dorfsmay** [comment]
Thanks! Let me know if you need me to test anything.

**Comment by dorfsmay** [comment]
Works. Thanks!

**Comment by hultmann** [comment]
Great, I just sent it to AMO (beta channel)

https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by k-bx** [comment]
Unfortunately, I'm still seeing it on 3.2.0.

**Comment by Komptrman** [comment]
I'm seeing the problem where new tabs created through the (+) button in the Tabs toolbar will open the new tab in the wrong profile. It doesn't do this in all windows. Just some. If I right click on a link in a page and select Open Link in New Tab, or wheel click the link to open the link in a new tab, then the new tab will open in the same profile as the tab that the link was launched from.

I'm using FF 37 and MF 3.2.0.

**Comment by k-bx** [comment]
Yeah, I can confirm this. Cmd+T will open default profile, while Ctrl+Click will keep current one.

**Comment by hultmann** [comment]
@Komptrman which OS?

**Comment by k-bx** [comment]
(If needed, for me it's OSX)

**Comment by Komptrman** [comment]
I am using Win7 on this computer. I have other computers with Kubuntu and WinXP, but I haven't checked them for this particular problem. They all have the problem with tabs not restoring to the correct profile when Firefox restarts. The first tab in the window will always be the correct profile, but other tabs often will not.

**Comment by hultmann** [comment]
Currently working on #207.

@k-bx Tab Mode or Window Mode?

**Comment by k-bx** [comment]
@hultmann tab-mode

**Comment by hultmann** [comment]
@k-bx please subscribe to #207.

This bug has fixed window mode. Apparently window mode it's working properly.

**Comment by Komptrman** [comment]
MF 3.2.0 may have fixed the problem of additional tabs not opening in the proper profile if started from the (+) New Tab button in the Tabs bar. I haven't seen it in a few days.
