### ISSUE TITLE
Tab does not inherit profile (Tab Mode)

### ISSUE THREAD

**Issue by calikazi** [hultmann/multifox#207]
In previous versions of Multifox, links that open a new tab/window through javascript were opening them in the profile of the parent window.  With this latest update, that has changed.  Each new tab/window now goes back to the default profile.

I am currently using Multifox 3.2.0, and I just validated (tested while writing this) that Multifox 3.1.0 does not have this error.  I will use it in the meantime.

Thank you for all of your work on this.  It is an impressive addon.

**Comment by hultmann** [comment]
So all middle click tabs don't inherit the profile id?

Couldn't be related to issue #203 (window mode)? Are you using OS X?

**Comment by calikazi** [comment]
This is left click where javascript forces a new tab/window.  (I do have Firefox set to force new windows into new tabs).  Middle click works well with this addon.  Window mode is turned off.

**Comment by hultmann** [comment]
I can reproduce it. Investigating...

**Comment by hultmann** [comment]
Please try 3.2.1b1 
https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by calikazi** [comment]
This appears to fix the problem.  Thank you!

**Comment by k-bx** [comment]
Yay! Fixed.
