### ISSUE TITLE
Problem in 3.2 while opening windows

### ISSUE THREAD

**Issue by mohebfouad** [hultmann/multifox#208]
In 3.1
when you open a window from multifox user, it was opening with the same user
in 3.2
when you open a window from multifox user, it opening with the the primary user

that cause a lot of problems

**Comment by hultmann** [comment]
Probably fixed by #207, please try 3.2.1b1
https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by mohebfouad** [comment]
Thanks ^^
