### ISSUE TITLE
How to Export/Import Multifox Profiles?

### ISSUE THREAD

**Issue by ReporterX** [hultmann/multifox#209]
How can I export/import Multifox profiles from one Firefox to another?

It would be great if export/import feature is available.

 Thank you.

**Comment by hultmann** [comment]
There are at least 2 options: Firefox Sync (not sure if it works properly...) or copy extensions.multifox@hultmann.alias from about:config

**Comment by ReporterX** [comment]
It does not seem like it works properly, but it was long time ago I tried it. Did you try it recently?

An internal export/import function is preferred for people who just want to export/import this addon's setting.

**Comment by hultmann** [comment]
Yes, if by "long time ago" you mean years.
