### ISSUE TITLE
New tab lose Profile from target="_blank" link 

### ISSUE THREAD

**Issue by ili101** [hultmann/multifox#210]
Hi
This started after moving from version 2 to version 3.2

(Tab Mode)
Start a new tab
select a multifox profile
go to for example http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target
Click "Visit W3Schools.com!"
It will be open in a new tab without the profile of the parent tab

note that if you right click the link and select open in a new tab it will open the new tab with the parent profile as expected

**Comment by hultmann** [comment]
Fixed by #207. Please try 3.2.1 beta and let me know if it works properly
https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/

**Comment by ili101** [comment]
Thank you!
