### ISSUE TITLE
Twitter auto log out, error re use of indexedDB

### ISSUE THREAD

**Issue by JulianSMoore** [hultmann/multifox#219]
Compliments: I love the idea of this, nicely done! 

Unfortunately, whilst it obviously works well for most people, something isn't working for me. Hope you can help.

Issue: Set up several profiles (profile used has no effect on the following)

After successfully logging in to Twitter (which takes several attempts, via login error retry pages; this only occurs since Multifox installation), I am automatically logged out again after a few seconds. Multifox indicator becomes a white cross in a red circle when Twitter has loaded, error message is:

"this page may not work with a MultiFox profile because it uses a **feature not supported (indexedDB)**

Indicator then becomes standard again when I have been logged out and returned to a login page.

The use of indexedDB must be peculiar to my setup somehow... if you can shed any light on the matter than would be great.

I expect it is an add-on conflict: here's the config: Win 7 64-bit, FF 38 with addons:

about:addons-memory
BetterPrivacy 1.68-1
CodeBurner for Firebug 1.6.1
Exif Viewer 2.00.1
Firebug 2.0.11
Ghostery 5.4.5.1
Keyword Seach 1.1.5.1
Multifox 3.2.1
NoScript 2.6.9.27
Self-Destructing Cookies 0.4.7.1
SZession Manager 0.8.1.6.1m User Agent Swticher 0.7.3.1
Zotero 4.0.26.4

[AdBlock plus is installed but disabled: I am trying out a hosts file replacement to block ad sources]

Best regards
Julian

**Comment by JulianSMoore** [comment]
Udate: the auto logout was being caused by Self-Destructing cookies deleting xxx.multifox and I couldn't find a way to whitelist multifox so I disabled Self-Destructing cookies and restarted.

The indexedDB error is still there but multiple Twitter accounts stay logged on)

Julian

**Comment by berrythesoftwarecodeprogrammar** [comment]
why not just 'temporarily suspend operation'? thats what i do when using accounts on multifox

**Comment by hultmann** [comment]
Closing this since Multifox is not being developed anymore due to [deprecation of XPCOM extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).
