### ISSUE TITLE
Re-adding Pale Moon support please!! 

### ISSUE THREAD

**Issue by LimboSlam** [hultmann/multifox#225]
Hi there! 
This add-on was great when I still used Firefox! Now I use Pale Moon (an open source web browser forked off from the Firefox/Mozilla code), my all time favorite browser!!!! But sadly it's not compatible with it anymore mostly because AMO wrongly states, "Your using an outdated version of Firefox that is no longer supported, Firefox 24.9." Now this is somewhat true as we are forked off from the Firefox v24.0 code and onward from Pale Moon v25.0. We have done this by changing our GUID (a dual-GUID system to support both FF and PM exclusive add-ons) to reflect a divergence from Firefox and that we don't support and will not implement the Australis design/theme. I also want to mention that we are in the works of a new layout and rendering engine called Goanna (a modified rendering engine to fit our specific needs and is different enough that we can give it a new name). Now I believe a simple change to the chrome.manifest or bootstrap.js to add/change to the hard-coded GUID could be the solution here, well as long as you guys don't only target the new technology Pale Moon has chosen not to implement (australis design/theme, new features and technology in the current Firefox)?? You can also lower the the requirement version to v24.0 and see if still functions. Maybe you could write a compatibility layer to keep support for us?  

-Our GUID is: {8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}
-Firefox compatible UA string is: Mozilla/5.0 (Windows NT 6.1; rv:25.6) Gecko/20150723 Firefox/31.9 PaleMoon/25.6.0
-Pale Moon UA string is: Mozilla/5.0 (Windows NT 6.1; rv:25.6) Gecko/20150723 PaleMoon/25.6.0

To implement a simple change to the chrome.manifest or bootstrap.js to add/change the hard-coded GUID, please read this: https://forum.palemoon.org/viewtopic.php?f=24&t=8740 and for more info on the Goanna engine, please read here: http://moonchildproductions.info/goanna.shtml. 

Thanks for this wonderful add-on you have provided for Firefox!! Really appreciate it! :) I just hope support is added and if not now maybe in the near future as Pale Moon v26.0 is released this winter; a whole new product!!

**Comment by hultmann** [comment]
Sorry, I barely can keep Multifox working with Firefox itself: https://github.com/hultmann/multifox/issues/215#issuecomment-126537223

Anyway it would be a lot of work as current Multifox uses methods from Australis to render button/menus.

BTW, Mozilla is implementing Chrome API for extensions, I suggest Pale Moon implements it as well so virtually all Chrome extensions could be easily ported to Pale Moon.

**Comment by LimboSlam** [comment]
That's quite alright! I know how hard it is keeping up with Firefox RDR's and thanks for the tip, it will surly be up to debate soon as we transition to a whole new browser and improve our add-on platform. 

One more question, would you please direct all Pale Moon issues to this thread so they know about both of our stands. Plus if any add-on dev(s) come across this they too know about this alternative browser and are free to develop Pale Moon specific add-ons or add a compatibility layer to keep support for us. This is just suggestion though.  

Thanks for hearing me out and for this wonderful add-on you have created!! Maybe in the feature we can work together on getting this one to support Pale Moon and host it on our add-on site. 

If you have any other suggestions or questions concerning the Pale Moon Project, please feel free getting in contact with us through our forum and our homepage, which can be found here: https://forum.palemoon.org/index.php and here: http://www.palemoon.org/contact/. We are also on Facebook and Twitter.  

Best regards, 
LimboSlam
