### ISSUE TITLE
issue working with another extension called xkit

### ISSUE THREAD

**Issue by hanharr** [hultmann/multifox#226]
i recently started using multifox to use a few different accounts on tumblr without having to log back in and out constantly and multifox is doing an awesome job for that. however there's an extension i've been using with tumblr since, well, i started using the website, to make it a lot more efficient. xkit's known to have problems working with multifox and even the new version that's been created and updated to sort out the most recent slew of problems has issues with it. xkit will work when i'm using my default profile but not when i use any of my other profiles. i contacted the developers for the new xkit extension here on github first and here's what they said with regards to the issue:

<img width="781" alt="screen shot 2015-08-05 at 11 03 08 pm" src="https://cloud.githubusercontent.com/assets/13610796/9104861/2b4734ac-3bc6-11e5-8c42-82983b4e6503.png">

i'm hoping they're right and it's something that can be solved in multifox?

**Comment by DamienHelvian** [comment]
Up until now, for me, there hasn't been too many problems with XKit, aside from not being able to use XInbox on non-default profiles. But that isn't too big of a thing.
But now, with the countless terrible tumblr updates, and the new extension Editable Reblogs fixing problems, Multifox isn't happy with it anymore, making it pretty much impossible to actively reblog posts, and only allowing Alt-reblogs.
I myself have sent reports to XKit and they say that it would be on your side. Something about not handling XHRs correctly.

**Comment by hultmann** [comment]
Multifox is not being developed anymore due to [deprecation of XPCOM extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).

What I can do is mark xkit as incompatible, so that users will be warned.
