### ISSUE TITLE
Re-opened tabs at startup

### ISSUE THREAD

**Issue by paulclaude** [hultmann/multifox#228]
It would be useful if, on startup, each tab could remeber the active profile when Firefox was closed last time.

**Comment by hultmann** [comment]
This is what happens since Multifox 1.0, actually. Maybe an extension conflict?

Closing this since Multifox is not being developed anymore due to [deprecation of XPCOM extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).
