### ISSUE TITLE
[question] is there any way for other addons to detect multifox tabs and the cookies which belong to them?

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [hultmann/multifox#230]
https://github.com/hultmann/multifox/issues/219 related

addons such as 'self-destructing cookies' and 'umatrix' are unable to match multifox cookies to any tabs as they have the domain.multifox suffix which cant be mapped to any tabs, therefore multifox cookies are deleted when these addons delete 'unused' cookies. 

is there anything multifox does to a tab such as set certain data which could be accessed by other addons so they can know that the tab is a multifox tab and map the cookies to them? this isnt a problem with multifox, its a problem with other addons. but if multifox is missing the ability to let other addons know about its tabs then that should be added i think

**Comment by hultmann** [comment]
Sorry, Multifox is not being developed anymore due to [deprecation of XPCOM extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).

That said, I don't think it would be possible due to amount of hacks Multifox needs.
