### ISSUE TITLE
[Feature request] Designate a domain to always open in a particular profile

### ISSUE THREAD

**Issue by HighCommander4** [hultmann/multifox#231]
It would be useful to be able to associate with each profile a list of domains, such that whenever you navigate to a page in a given domain (like 'example.com'), it opens in that profile regardless of what profile you're coming from.

**Comment by hultmann** [comment]
Sorry, Multifox is not being developed anymore due to [deprecation of XPCOM extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).

However, I'll try to keep Multifox working until e10s reaches a Firefox release (Firefox 50? 60?).

**Comment by HighCommander4** [comment]
> Sorry, Multifox is not being developed anymore due to deprecation of XPCOM extensions.

My understanding is that transition is quite far off. That said - is it not possible to modify Multifox to use the new APIs?

**Comment by hultmann** [comment]
Probably it will not be possible (currently it isn't). Anyway, Multifox would need to be totally rewritten.
