### ISSUE TITLE
A possible solution to deprecation of XPCOM extensions: Pale Moon? 

### ISSUE THREAD

**Issue by VeronicaGarcia** [hultmann/multifox#232]
Hi there, hows your morning going. Hope good.  :) 

I'm one your users and so I would like to know if you have any back-up plans once this hits a stable version of Firefox by next year sometime?     

I only have one solution to offer up that may be feasible, and that is to switch your development to the Pale Moon project. I hear they will continue support for XPCOM and XUL for add-on developers that use this source code to build their powerful extensions that we all have come to love and rely on. See here: https://forum.palemoon.org/viewtopic.php?f=26&t=8756 (couldn't find the exact line, but if you read the beginning and on, he's clearly against it) and to know more about how to support Pale Moon/Goanna (a modified rendering engine to fit their specific needs as an independent browser) properly: https://forum.palemoon.org/viewtopic.php?f=24&t=9077.

Now I have both Firefox (ESR v38.4) and Pale Moon (v25.7.3) installed and I love them both, but I don't agree with the direction Mozilla going with Firefox anymore. So once add-on signing is forced upon me and deprecation of XPCOM/XUL extensions lands in Firefox by next year sometime, I will put a stop to Firefox updates or fully switch over to Pale Moon and uninstall Firefox in which you will have lost a user and many more to come.

This right here is straight up the hard truth and I have heard of many other developers planning the switch to Pale Moon once this hits Firefox. Two quick examples of this can be found here: http://imagehost-grabber.org/index.php?topic=3479.0 and here: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/comment-page-4/#comment-219018. But we'll see by next year to come. 

So in all best regards,
VeronicaGarcia  :)

**Comment by hultmann** [comment]
Thanks for your suggestion. But I lost the interest in development of this extension. :|

**Comment by VeronicaGarcia** [comment]
Your welcome. Just know there is at least one alternative to for your hobby or job to survive.  :)
