### ISSUE TITLE
Menu does not work if navigation bar is hidden

### ISSUE THREAD

**Issue by wisq** [hultmann/multifox#233]
I use Vimperator, which historically has meant that I run Firefox with no navigation bar.  In particular, this is my mapping for `F2`, which toggles the navbar on and off:

```
map <silent> <F2> :js toggle_navbar()<CR>
:js << EOF
function toggle_navbar() {
    var nb = document.getElementById('nav-bar');
    if (!nb)
        return;
    nb.style.visibility = (nb.style.visibility == '') ? 'collapse' : '';
    nb.style.overflow = (nb.style.height == '') ? '' : 'hidden';
}
toggle_navbar();
EOF
```

Now, given that I have no nav-bar, I moved Multifox down to the add-on bar, as recreated by the plugin `The Addon Bar (restored)`.  It works fine down there:

![mozilla firefox - vimperator-3](https://cloud.githubusercontent.com/assets/255758/11196973/5cbf1104-8c88-11e5-8077-a21d10decb77.jpg)

However, if I actually want to access the Multifox drop-down and change profiles, I need to enable the navbar first; otherwise, clicking does nothing.

I know I've got a pretty weird setup, but I'm hoping this is an easy fix — all my other plugins and their menus work fine down in the addon bar (you can see I have plenty), and this is the first addon I've ever had this problem with.

**Comment by ghost** [comment]
Same problem here. The menu doesn't open without the navigation bar being displayed. My Multifox button is in the tab bar (Iceweasel 38 and 42 on Debian 8.2, Multifox 3.2.1, Vimperator 3.10.1).

An unrelated note: there is an easier way to toggle your navi bar in Vimperator.  Just add a line to your ~/.vimperatorrc:
map ,n :set gui=invnavigation<cr>

**Comment by wisq** [comment]
Thanks, that's much simpler.

As a workaround, I created commands to change profiles.  It's a bit of a gross hack, but it generally works okay: https://gist.github.com/wisq/521731c3395810cb23db

The only downside is, sometimes the profile change doesn't quite "take" and you need a second page reload to make it happen.

**Comment by hultmann** [comment]
Sorry, Multifox is not being developed anymore due to [deprecation of XPCOM extensions](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/).

However, I'll try to keep Multifox working until e10s reaches a Firefox release (probably at some point in 2016.).
