### ISSUE TITLE
Multifox Error in Yahoo Mail

### ISSUE THREAD

**Issue by mrap123** [hultmann/multifox#234]
Multifox 3.2.1
Firefox 42.0

When trying different multifox profiles in yahoo mail, the mail tabs (notes, calendar, etc) and actions (reply, move, etc.) do not work for any other saved profile other than the default profile.  When logging in and out of different yahoo email accounts under the default profile, there is no problem.  

Thanks!

**Comment by hultmann** [comment]
It's fixed in version 3.2.2beta: https://addons.mozilla.org/en-US/firefox/addon/multifox/versions/
