### ISSUE TITLE
Multifox not working in Firefox Developer Edition, even with e10s disabled

### ISSUE THREAD

**Issue by HighCommander4** [hultmann/multifox#235]
I understand that Multifox is not yet expected to work with e10s enabled (https://bugzilla.mozilla.org/show_bug.cgi?id=1047432).

However, I'm finding that it doesn't work in Firefox Developer Edition even after I disable e10s (in Preferences -> General -> Startup). Pressing the Multifox button just brings up an empty menu.

It works fine in Firefox Beta.

**Comment by hultmann** [comment]
Fixed by Multifox 3.2.2. (released today) :)
