### ISSUE TITLE
Multifox issues with Xkit for Tumblr

### ISSUE THREAD

**Issue by fionaroleplays** [hultmann/multifox#236]
Just letting you know, Multifox is not compatible with Tumblr anymore if you use New Xkit. I have spoken with New Xkit and they say it's not a problem their end, so must be an issue with Multifox. I am also getting the multifox logo anymore, just a red button with a white X, though still works. I can't reblog on Tumblr, that's the main problem.

**Comment by hultmann** [comment]
It's #226. If you click the Multifox button (white X) > Show Error, you should see the incompatibly message.
