### ISSUE TITLE
Addon signing required for new versions of firefox

### ISSUE THREAD

**Issue by dasl-** [hultmann/multifox#241]
In order to install this addon in new versions of firefox, the addon must be signed.
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by hultmann** [comment]
It's already signed. Where are you downloading it from?

**Comment by dasl-** [comment]
Oops, I meant to post this on your allacounts github project. Sorry I will re-post the same comment there.

**Comment by dasl-** [comment]
I've created the new issue here: https://github.com/hultmann/allaccounts/issues/17
