### ISSUE TITLE
I got message "This page may not work..."

### ISSUE THREAD

**Issue by paulclaude** [hultmann/multifox#244]
I got message "This page may not work with a Multifox profile because it uses a feature not supported (IndexDB), when loading "http://www.deleted.io". And the page http://www.deleted.io can't load the FB info. There's a way to disable Multifox for that page?

**Comment by hultmann** [comment]
Yes, just use the default profile and the page should load properly.

**Comment by nunpiyu** [comment]
i got same issue today. the problem come again when open another page. again and again
solved only when move the page to default page like you said. bu then what multifox made for (if every page have to place to the default one)
oh update. i can log in to the site finally. I downgrade the multifox to beta vers release on June

**Comment by nunpiyu** [comment]
i got same issue today. the problem come again when open another page. again and again
solved only when move the page to default page like you said. bu then what multifox made for (if every page have to place to the default one)
oh update. i can log in to the site finally. I downgrade the multifox to beta vers release on June

**Comment by nunpiyu** [comment]
but the error message still there haha

**Comment by nunpiyu** [comment]
got worse. i even only can open 7 page normally on tokopedia.com
can not log in more than 7. whats going on ?
