### ISSUE TITLE
Open session automatically in a new tab

### ISSUE THREAD

**Issue by ghost** [hultmann/multifox#245]
Hi!

First of all: Great plugin - thanks for that. 
I´ve one suggestion: We plan to use this plugin for our ERP system where our users are working with multiple session in different tenenat on different tabs.

So if it´s possible to create a toolbar icon which automatically opens a new tab as seperate session would be a big help.

Great work,
Thanks,
Michael

**Comment by hultmann** [comment]
Sorry, Multifox is not in development anymore. I'm fixing only compatibility issues with new versions of Firefox,

**Comment by EveFromFrance** [comment]
tooooo sad!!!
