### ISSUE TITLE
Selected client certificate spills over sessions

### ISSUE THREAD

**Issue by xerces8** [hultmann/multifox#246]
If I login to a website with one certificate, the switch to a new session and visit the same website I can not login with other certificate, the first one is used automatically. If I clear auth (ctrl-shift-del "Active Logins") in one session, and reload and select the second certificate, the certificate is changed in first session too.

Test site:
https://www.bennish.net/certs/

Using v3.2.2.1-let-fixed on FF 45.0.2 on Win7SP1-64bit

**Comment by hultmann** [comment]
Sorry, it's a known limitation of Multifox.
