### ISSUE TITLE
[Feature Request] add profile attribute/class/etc to tab.tabbrowser-tab

### ISSUE THREAD

**Issue by My1** [hultmann/multifox#248]
well saying it simple it would be pretty epic if there could be different attributes or similar to distinguish different profiles in CSS. that way we could customize the tab style depending on the profile using tools as stylish.

funfact: I already use the "Private tab" extension which also throws an attribute and allows me to customize its appearance. would be rather epic if multifox had a similar feature.

thanks

**Comment by hultmann** [comment]
Sorry, Multifox is not in development anymore. I'm fixing only compatibility issues with new versions of Firefox,

**Comment by My1** [comment]
that's too sad.

**Comment by EveFromFrance** [comment]
Aaaaargh  :( but i'm using the 47.0 version

C'est trop dommage

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Garanti
sans virus. www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-06-20 2:18 GMT+02:00 Jeferson Hultmann notifications@github.com:
