### ISSUE TITLE
Issues with New XKit

### ISSUE THREAD

**Issue by gloomykid** [hultmann/multifox#249]
New XKit is unable to be used on sessions of MultiFox. 

![ss 2016-05-25 at 04 10 20](https://cloud.githubusercontent.com/assets/13604430/15542950/36a0690e-2293-11e6-9a7e-141d8f2042bb.jpg)

Screenshot is in German, but it basically warns about interferences between MultiFox and New XKit.

**Comment by hultmann** [comment]
See issue #226
