### ISSUE TITLE
Enable functionality for tabs, not just windows

### ISSUE THREAD

**Issue by particleman** [hultmann/multifox#25]
I would like to see new profiles in new tabs, not just new windows.  For those of us that do most of our work in tabs, and like ctrl-pgup/pgdwn movement, this would make our lives a lot easier.

**Comment by tbs** [comment]
Try version 2 to see this in action :D

http://br.mozdev.org/multifox/all.html

**Comment by hultmann** [comment]
I'm closing this bug on tbs's comment. :)
