### ISSUE TITLE
Mouse-right-click menu open link not works since Firefox 47.0

### ISSUE THREAD

**Issue by jiripolacek** [hultmann/multifox#251]
Hi,

please fix this issue: if I right-click the mouse and then "open link in new identity profile" > "profile 2/default/etc." nothing happens. In Firefox 46.x it works. Since Firefox 47.x nothing.

Thanks,
Jiri

**Comment by iking1** [comment]
Having the same issue as well

**Comment by EveFromFrance** [comment]
Zut alors.. J'en suis désolée ))):

No way to make it work as before?

---

Envoyé depuis mon mobile samsung

**Comment by hultmann** [comment]
Thanks for the report, I'll fix it. :+1:

**Comment by hultmann** [comment]
Fixed, please test it:
https://addons.mozilla.org/firefox/addon/multifox/versions/beta

(There are also fixes for upcoming versions of Firefox, so please test it with Firefox Beta, Developer Edition, and Nightly if you can.)

**Comment by iking1** [comment]
Seems to be working good on my end. Thanks a bunch!
