### ISSUE TITLE
Active Logins are not cleared for non-default profiles

### ISSUE THREAD

**Issue by bodywithoutorgans** [hultmann/multifox#254]
When in browser setting: clear history on Firefox shutdown I check "Active logins", the logins are cleared only for the default profile. In other profiles I stay logged in after closing and starting the browser.

**Comment by hultmann** [comment]
hmmm.... Multifox doesn't support what Firefox calls "Active Logins" (sorry, it's a known limitation).

Check "Cookies" to remove Multifox data.
