### ISSUE TITLE
submit and open in a new profile

### ISSUE THREAD

**Issue by riajul74** [hultmann/multifox#258]
Hi, i have installed multifox addon and i can open new profile in separate tab. what i want to do, i want to submit a form and that form will should open into new profile with submited data on original profile.

example i am on a tab Profile -1 i will fill a form. and when i will submit the form, it will open on new tab on Profile-2 , with the information data i have entered Profile-1 does it possible ? 

![2016-12-01-22-47-09-44a50f](https://cloud.githubusercontent.com/assets/24405835/20917016/3f3beab0-bbb9-11e6-895e-1c2c9580f477.png)

** Multifox is not in development anymore and it won't be compatible with e10s **
** Please submit an issue only if you have found a regression **

**Comment by riajul74** [comment]
anyone can help me please ?

**Comment by hultmann** [comment]
addons.mozilla.org will stop accepting classic extensions (like Multifox) in Firefox 53.

Multifox will stop working after Firefox 56.

Sorry, there is no point in adding new features. Let Multifox die peacefully.
