### ISSUE TITLE
Doesn't work in Firefox 53+

### ISSUE THREAD

**Issue by pintassilgo** [hultmann/multifox#266]
Cause:
https://hg.mozilla.org/mozilla-central/rev/e3c689dbcd92

Fix:
_/modules/main.js, line 125_
```
-    return ((t === "content-targetable") || (t === "content-primary"))
+    return ((t === "content-targetable") || (t === "content-primary") || (t === "content"))
```

**Comment by hultmann** [comment]
Mozilla removed Multifox from AMO (probably for being e10s-incompatible).

Unfortunately this is the end for Multifox.
