### ISSUE TITLE
Not working on Firefox 5.01

### ISSUE THREAD

**Issue by francwalter** [hultmann/multifox#29]
I just installed Multifox 1.3.1 on Windows XP SP3 Firefox 5.0.1 and on a MacBook with OS X 10.6.8 and on both Multifox is NOT working.
I have the entries in the context menu, and when I click it I get a new tab, but without the Multifox number-icon.
When I switch to a tab with another google login and I reload that page, then this tab will be the login of the just opened Multifox Tab. It should keep its old login.
The tabs use still the same cookies, so there no way to use different accounts in different tabs with Multifox.
I have Tab Mix Plus installed and some other Add-Ons, maybe they interfere but I won't uninstall them.

**Comment by hultmann** [comment]
Probably it is related to some extension. Which are they?

**Comment by francwalter** [comment]
I understand now. Multifox does nothing more than just to open a new Firefox WINDOW.
In this new window I can connect to a different account of the same service (e.g. google mail etc.).
It is just a new window and nothing more, that is why. For three different accounts I would need three different windows!

I am using TabMix Plus which lets only one window open, new windows are forced to open in a new tab, which is much more handy.
But Multifox cannot handle different sessions in different tabs, like it was possible with the older Add-On called "CookieSwap" which is unfortunately not anymore compatible with Firefox 5.

Then I will uninstall Multifox again and wait, until Multifox is able to handle this on different TABS in one same window if this is ever planned.

**Comment by hultmann** [comment]
Yes, if you have only one window then there is only one identity.

You may be interested in trying out Multifox 2 beta, it is designed to work with per tab identities: http://br.mozdev.org/multifox/all.html
