### ISSUE TITLE
Unable to log in to specific sites

### ISSUE THREAD

**Issue by astateofblank** [hultmann/multifox#3]
With the plugin enabled, I'm unable to login to these specific sites:

https://www.texasgasservice.com/
https://www.ahm-ownerlink.com/
https://www.att.com/olam/dashboardAction.olamexecute?customerType=U

For the Honda site, I'm seeing this error in Firebug:
uncaught exception: Error: console.assert - INPUT name-=Password getBoundingClientRect().width0 - false
Line 0

For Texas Gas Service, its:
uncaught exception: Error: console.assert - INPUT name-={2} getBoundingClientRect().width0 - false

For the AT&T Uverse login, its:
console.assert - INPUT name-password=[removed] getBoundingClientRect().width0 - false
resource://multifox-modules/new-window.js
Line 191

Thanks for the great work - I'm a big fan of the way 2.0 is implemented.

**Comment by hultmann** [comment]
Thanks, this is going to be fixed in beta 2.

**Comment by hultmann** [comment]
This is fixed in Multifox 2 beta 2. Let me know if problem still persist.
