### ISSUE TITLE
Updated code? (on github)

### ISSUE THREAD

**Issue by phillbaker** [hultmann/multifox#30]
Doesn't look like the code here reflects 2.0b3 or 2.0b2. Mind pushing your latest? I'd like to play with it/hack it to my personal idiosyncrasies...

**Comment by hultmann** [comment]
It's my plan for the next weeks. The code needs some clean up. :)

**Comment by phillbaker** [comment]
Thanks for all your work on this! Whether the code is clean or not though, it'd be really cool if you could push it - I've been looking at the source from the extension and have some changes I'd like to make. But with all of the main modules condensed, it's a little hard to work with. If anything, more folks could help clean it up if you share!

**Comment by hultmann** [comment]
Sorry for taking too long. I won't be able to start up development again until September/October, my next task will be pushing Multifox 2b3 to github.

**Comment by studgeek** [comment]
Great! To be clear though, are you saying you won't get to work one exposing the code until Sep/Oct? Or that you can expose the code sooner, but won't be able to do more work yourself until Sep/Oct?

**Comment by hultmann** [comment]
I won't do anything related to Multifox code until Sep/Oct.

**Comment by hultmann** [comment]
Update: I need to release Firefox 8-10 compatible versions (Fx8 is just around the corner). Then, I'll fix this bug.

**Comment by hultmann** [comment]
It's going to be fixed during the next days! Give me some time to remember how Multifox works. :o)
