### ISSUE TITLE
multifox 2 source code on github

### ISSUE THREAD

**Issue by studgeek** [hultmann/multifox#33]
I see at https://github.com/hultmann/multifox that "Multifox 2 source code on GitHub soon", I'm just adding this issue to hopefully track when that happens :). Also so others will see its not available yet, I clicked around a lot before I saw that comment. Thx.

**Comment by studgeek** [comment]
Note, the source code link off the beta about page is broken also (https://github.com/hultmann/multifox/tree/2.0b3), possibly because that branch is still private?

**Comment by hultmann** [comment]
It is https://github.com/hultmann/multifox/issues/30

https://github.com/hultmann/multifox/tree/2.0b3 is broken because the build script assumes the source is available on github. :)
