### ISSUE TITLE
Compatibility with Menu Editor

### ISSUE THREAD

**Issue by JinxDojo** [hultmann/multifox#37]
I recently installed Firefox 5.0.1 and discovered the "open in new identity profile" link was missing.

After a bit of testing, it appears that, despite getting along in Firefox 3.6, Multifox and Menu Editor don't like each other in Firefox 5.0.1.

Is there any chance at fixing this? Has it perhaps already been fixed in the betas? (I should note that I have only tried version 1.3.2.)

Thank you very much for working on this extension; I cannot believe after all these years Firefox hasn't implemented this natively. Despite what they say: identity profiles are simple to understand, and very useful! Thanks again.

**Comment by JinxDojo** [comment]
This issue is still persistent in FF version 6.0+. Is there any fix planned?

I noticed this was marked "Classic"; does that pretty much mean abandoned? If so, any chance of getting the beta version ready for prime time?

**Comment by hultmann** [comment]
I just renamed "Classic" to "Multifox 1.x".

Multifox 1.3.2 is still supported, but Multifox 2 bugs have priority.

**Comment by JinxDojo** [comment]
That's good news. Hopefully this bug can get squashed or isn't present in version 2. I look forward to either result.

**Comment by JinxDojo** [comment]
I don't think I closed this? I only made a comment on October 3rd, 2011.

**Comment by hultmann** [comment]
Good news, it is almost fixed. Unfortunately, it seems it is possible to fix the File menu, but not the link context menu.

**Comment by JinxDojo** [comment]
Did you mean vice-versa? I'm now on Firefox 7 and using Multifox 1.3.3, and the link context menu works great, but the File menu item is absent (despite being present in the list that "Customize Menus" provides).

This behavior is just fine by me, though. Thank you for fixing the issue, and thanks again for this great extension.
