### ISSUE TITLE
unstable identities

### ISSUE THREAD

**Issue by kaskuser** [hultmann/multifox#4]
here's the condition :
1st test :
- opening 3 facebook account for playing games on 1 FF window (tab 1 : account A, tab 2 : account B, tab 3 : account C)
- after several times, the identities disappear and it's all mixed up one to another (tab 1  became account B, tab 2 became account C, tab 3 became account A, for example)
- need a refresh or back to facebook.com page but after a period of time it's all mixed up again

2nd test :
- opening 3 facebook account on new windows (1 window = 1 account)
- the problem still remain the same

hopefully can help you develop a better one, sorry for my bad english ^^

**Comment by hultmann** [comment]
Thanks for the report! I'll have to investigate that one a little further.

**Comment by hultmann** [comment]
kaskuser, what language do you use in Facebook? Can you check if the bug still appears with Facebook in English?

**Comment by hultmann** [comment]
Does it still happen with Multifox 2 beta 2?

**Comment by hultmann** [comment]
Closing this bug due to lack of feedback.
