### ISSUE TITLE
Manually change/rename profile

### ISSUE THREAD

**Issue by techmunk** [hultmann/multifox#42]
When developing our sites we use a master "super" account that has the ability to change to other accounts without knowing the password of the account. This bypasses the login detection method that multifox uses. It would be really cool, if we could simply "rename" the multifox profile being used, so that we can login again with the same account, but have a different session/profile.

Does that make sense? Would this be possible to do?

**Comment by techmunk** [comment]
Just to clarify a bit more, I'm wanting to be able to have multiple sessions for the same username/login, but be able to rename the session name displayed in the address bar.

**Comment by hultmann** [comment]
At first glance this behavior seems incompatible with how Multifox works internally.

I'll keep this bug open for further investigation.

**Comment by Drugoy** [comment]
I'd like to be able to rename accounts in order to change their sorting. Currently they get alphabetically sorted and you can't do anything with that.
