### ISSUE TITLE
Blacklist and Whitelist

### ISSUE THREAD

**Issue by tymofij** [hultmann/multifox#44]
Multifox works great on Twitter, and it totally replaced Echofon for me. Thank you very much.

However, that is the only site where I need multiple identities, and I would like to disable it on others, so my address bar would be clean.

And also, Multifox breaks my Livejournal experience, so I can imagine one would want to disable it on LJ specifically.

Both of those problems could be easily solved with Blacklist - the list of sites where one does not want Multifox to run, or Whitelist - the list of only sites, where Multifox is permitted. 

I am running Multifox 2.0b3 on Aurora 8.0a2.

**Comment by hultmann** [comment]
Sorry, I need to keep the code as simple as possible in order to follow rapid Firefox releases.

So, no plans to implement whitelists/blacklists.
