### ISSUE TITLE
MultiFox 2.0b3 glitch, it duplicates sessions.

### ISSUE THREAD

**Issue by SuperMrTech** [hultmann/multifox#45]
its hard to explain so i recorded it.

http://www.youtube.com/watch?v=cM9Bv-qte5E

**Comment by riyaah** [comment]
I get this as well, but for google-accounts. 
Let me know if you need help with testing.

**Comment by hultmann** [comment]
It seems to happen during a login.

**Comment by hultmann** [comment]
I just found the offending code, actually it was a typo!

**Comment by hultmann** [comment]
Already fixed in current beta (b5/b6).
