### ISSUE TITLE
Temporarily Disable MultiFox

### ISSUE THREAD

**Issue by a-raccoon** [hultmann/multifox#47]
I understand 2.0 is currently in Beta, and as such it's expected to break some sites (eg, eBay>PayPal and Etsy>Paypal and other sites that share cookies).  So I would like to request an option to Temporarily Disable the extension from a menu instead of having to disable the extension entirely and restart Firefox.

I realize I could ask to add further options like a site exemption list and other such filtering, but for now a simple "On/Off" switch would be great! ^_^  Thanks

**Comment by excuses** [comment]
I agree with this suggestion, and also offer another solution: A Multifox blacklist, to disallow it being used on certain sites that it has been known not to work on (I've just discovered it won't let me login to capitalone.com)

**Comment by MurzNN** [comment]
+1 for this feature too. Have problems with some sites, but it is very needed on other sites. Blacklist and/or whitelist will be very good!

**Comment by hultmann** [comment]
This will be addressed by #14
