### ISSUE TITLE
Multifox break sidebar browsing

### ISSUE THREAD

**Issue by 0rt** [hultmann/multifox#48]
When multifox is enabled,  browss in sidebar behaviar is very strange: no response(like google log-in page), affect the main window tab, and the cookies also wrong

**Comment by hultmann** [comment]
Are you using "load this bookmark in the sidebar" option?

Multifox 1.3, 2.0b, or both?

**Comment by 0rt** [comment]
2.0b3, and yes, 'load this bookmark in the sidebar'.
 Can you reproduce it on your machine?

**Comment by hultmann** [comment]
Yes, I found the offending code.

**Comment by hultmann** [comment]
Fixed by issue #77
