### ISSUE TITLE
(MultiFox 1.3, wishlist) Open an arbitrary identity profile

### ISSUE THREAD

**Issue by andrzej-r** [hultmann/multifox#50]
I like MultiFox 1.3, in particular its clean separation of identity profiles - one per window, and its lack of automatic identity assignment when visiting a website.

One limitation of 1.3 series, which gets in my way is that I have to open identity profiles sequentially. In order to get to the profile no. 6 I have to open 6 windows, which is rather tedious and leaves 6 mostly unused windows on my desktop.

I'd like to have the (File and context) menu extended to allow opening a window with an arbitrary profile number.

**Comment by hultmann** [comment]
Yes, it is possible to select the id number directly from Multifox 1.3 popup.
