### ISSUE TITLE
Twitter, Hotmail, Gmail, etc.. for Multifox 

### ISSUE THREAD

**Issue by ghost** [hultmann/multifox#51]
Multifox 1.3.3, Firefox 8.0

My twitter account won't save on my secondary profile(2) even I ticked (remember me) but saves on my primary profile (1)
My facebook and other accounts works..

[this is on second profile] If I opened my twitter and hotmail tab and did not close the tab when I close firefox, My account will be logged in when i turned on firefox 

[this is on second profile] If I closed my twitter and hotmail tab when I close firefox, My account will be logged out when i turned on firefox 

Please fix :)

**Comment by hultmann** [comment]
Does the bug still persist?
