### ISSUE TITLE
Provide a SeaMonkey installable version

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [hultmann/multifox#52]
Mozilla SeaMonkey is another flavor of Firefox (see http://www.seamonkey-project.org/start/ )
Please make your valuable extension compatible with it
See for example http://chrispederick.com/work/web-developer/history/firefox/ for a cross browser sample extension implementation

**Comment by hultmann** [comment]
Unfortunately it became clear that I wouldn't have the time to keep Multifox compatible with SeaMonkey.
