### ISSUE TITLE
Grooveshark and Multifox 2

### ISSUE THREAD

**Issue by tbs** [hultmann/multifox#53]
"Explore" content on Grooveshark (http://grooveshark.com/#!/music) isn't loading when Multifox is enabled. We need urgent a blacklist feature to disable login manager on problematic sites until we report issues here.

This is the best and most useful addon ever, is sad not to have the attention it deserves.

**Comment by hultmann** [comment]
Do I need an account to reproduce this bug?

**Comment by tbs** [comment]
Issue closed, was a false positie. Anyway blacklist is a must have, I still can't to pay Ebay item using Firefox.

**Comment by hultmann** [comment]
Multifox 2b5 will be restartless, hope it will make blacklist less necessary. :)

**Comment by tbs** [comment]
Well, restartless will not solve 100% of usage, but will help for sure. I hope you don't remove blacklist from your TODO list. And my dream is to see your addon on AMO pages. I'm absolute sure as 2+2 are 4 that, Multifox is good enough to figure among the 10 most popular extensions!
