### ISSUE TITLE
multi fox 2.0b4 bugged with yahoo answers,previous version worked like a charm

### ISSUE THREAD

**Issue by Francismays** [hultmann/multifox#56]
2.0b3 worked perfectly but version 2.0b4 keeps doubling the accounts and its all messed up.

**Comment by hultmann** [comment]
Is this bug only about duplicated entries in the menu?

**Comment by Francismays** [comment]
well it duplicates when you create an account and also when you sign in , in one.

also when you create the account it stays in "add account" it doesnt move

**Comment by hultmann** [comment]
duplicated accounts in menu are going to be fixed (bug #45).

**Comment by hultmann** [comment]
Does the bug still persist?
