### ISSUE TITLE
Problem on vBulletin forum sites.

### ISSUE THREAD

**Issue by jimmychann** [hultmann/multifox#57]
I'm not too sure about other sites, but this particular one that I frequent, http://forums.hardwarezone.com.sg , keeps logging me out when I'm on it with multifox. 

It would make me login again whenever I'm idle on the site for a period of time, maybe 1-2 mins. I understand that some sites logs you out after some period of inactivity, but this one is definitely unusual as the time is too short. It works fine when I'm not using multifox, and doesn't log me out even after hours.

Any idea what's wrong?

**Comment by hultmann** [comment]
Does the bug still persist?
