### ISSUE TITLE
Twitter Support

### ISSUE THREAD

**Issue by Skiewuff** [hultmann/multifox#58]
Multifox seems like a great solution.
I was looking to browse different accounts in one browser.
I didn't like the fact Multifox opens a new Firefox window for a new session (identity profile).
So I installed the beta version, which works different.
It was great for Gmail, for example, but didn't have support for other sites like Twitter. Upon logging in it didn't save it as a profile.

Any chance for Twitter support on the beta?

**Comment by hultmann** [comment]
Twitter seems to work fine for me using Multifox 2. I should release 2.0b5 soon (March), let's see if this bug still exists.

**Comment by hultmann** [comment]
Is this still an issue?
