### ISSUE TITLE
2.0b2 per tab identities: which one to use?

### ISSUE THREAD

**Issue by junkchandu** [hultmann/multifox#59]
i use MF primarily to log into multiple google accounts. in 2.0b2, i can do this in multiple tabs, rather than having to launch multiple FFs. But then MF (and I) gets confused as to which identity I am using when (e.g.) go to google maps. Awesome bar says the identity is X, but google maps shows me logged in as Y. I think the option to open separate FF instances is important, because many google programmes (maps, docs, etc) are linked to the gmail login one has used. If one has multiple gmail logins in the same FF instance, which one should google use?

**Comment by hultmann** [comment]
Multifox 2.0b4 sometimes leaks cookies to default identity. That probably is what is happening with you. It will be fixed by beta 5.

**Comment by hultmann** [comment]
BTW, are you really using 2.0b2? b4 is the current version.

**Comment by junkchandu** [comment]
I used 2.0b2, and not b4, because the message below b4 was scary (can break some sites...) ;-)

**Comment by junkchandu** [comment]
@hultmann : but you have not answered my question, which seems more like a design issue: if two tabs have two different gmail accounts opened, and one opens a 3rd tab to go to google maps, which identity will that tab assume?

**Comment by junkchandu** [comment]
@hultmann : but you have not answered my question, which seems more like a design issue: if two tabs have two different gmail accounts opened, and one opens a 3rd tab to go to google maps, which identity will that tab assume?

**Comment by junkchandu** [comment]
forgot to mention: I used 2.0b2 because the warning under 2.0b4 scared me. Trying b4 now.

**Comment by hultmann** [comment]
well, probably b2 will break more sites than b4. :) Are you using Firefox 11?

As of 2b4, Google Maps will use the last Google account viewed.

I'm closing this because it refers to a deprecated version. Please reopen if necessary.
