### ISSUE TITLE
No multi login on zope!

### ISSUE THREAD

**Issue by enricosecco** [hultmann/multifox#60]
Hi,
I'm developing a web application on zope/plone framework and my client is Ubuntu 11.10 with firefox 11.0 and Multifox 1.3.3
To test the application's functions with login with different privileges I msut login separately like different users.
For this reason I did installed Multifox, but ...
When I open a 'New identity profile' and I go on the site to test i find my self already login with the admin user, the user of an other profile.
Must I configure something to Multifox work correctly? Have Multifox some problem with zope/plone login system?
Just now I'm working opening my application with Chrome but it too have a unique session and so I have a max of 2 sessions: the first in Firefox to develop and the second in Chrome to test.
Best regards.

**Comment by enricosecco** [comment]
No, I must correct my post. 
The problem do'nt depend from Zope/Plone. 
Could be it depend from the IP address: If I connect at the same application with the name address Multifox run correctly, if I connect with the ip address any profile open the same account.

**Comment by hultmann** [comment]
Does the bug still persist?
