### ISSUE TITLE
Bleeding over

### ISSUE THREAD

**Issue by annoyed93** [hultmann/multifox#62]
Hey I enjoy Multi Fox immensely but I have noticed on some of the things I do it won't let me do one thing or have one feature that is auto and going on one account going on another account. Is there some way to prevent this? or is it unfixable?

Thanks Annoyed93

**Comment by hultmann** [comment]
Sorry, I don't understand what the bug is... Please include steps to reproduce the problem.

**Comment by Drugoy** [comment]
@hultmann I'd suggest you to close this issue, until the @annoyed93 gives some details of what this issue was about.

**Comment by hultmann** [comment]
Closing.
