### ISSUE TITLE
Multifox 2.0b4 Breaks capitalone.com Login

### ISSUE THREAD

**Issue by bondbeau** [hultmann/multifox#65]
I've found that when logging in to just one (not multiple) capitalone.com accounts, Multifox 2.0b4 causes the login screen to simply cycle back to the beginning...it never completes. Disabling Multifox fixes the issue completely.

Firefox 12.0 (was the same on FF 9.0.1 as well)
Windows 7 Ultimate 64-bit

**Comment by hultmann** [comment]
Multifox 2.0b5 will change a lot of things, let's see if this bug still persist.

**Comment by hultmann** [comment]
Is this still an issue?

**Comment by bondbeau** [comment]
Yes, I believe so Jefferson...I still cannot log into capitalone.com via
Firefox...and I believe Multifox is the cause because diabling it allows
normal function.

Moreover, some weeks ago Multifox also stopped preventing Youtube/other
Google products from tracking across the Firefox browser...because the
Multifox box no longer shows up so one can click it to add a new account.
I've resorted to keeping another browser open simply so I can run Youtube,
Google searches, etc. without them being associated to my primary profile.

On Wed, Oct 24, 2012 at 8:47 PM, Jeferson Hultmann <notifications@github.com

**Comment by hultmann** [comment]
OK, same issue as in #68. However, the website should still be usable.

**Comment by bondbeau** [comment]
#65: Still breaks capitalone.com (simply disabling the Multifox extension
and restarting Firefox fixes the login problem). Maybe there is some other
issue going on here as well, but if so you'd have to tell me how to test.

#68: Sounds similar to what I was describing but I do not have enough knowledge
to be certain...sorry about that. All I know is that with Multifox enabled
and logged to Gmail in one tab, a new tab with Youtube or another Google
produce would show the Multifox choice to choose a new identity for
that tab....but
more recently (last few months at least) one cannot choose a new idendity
because the Multifox box does not appear.

**Comment by hultmann** [comment]
The Google login bug is a different issue. BTW, Google+ seems to be totally broken in Multifox 2.

**Comment by hultmann** [comment]
Multifox should not break the site now.

**Comment by bondbeau** [comment]
Correct, Capital One doesn't break it anymore!!!

Thank you Jeferson!

You know...of all things though, I've gone back to using another browser
for simultaneous Google products...as Youtube for example...still DOES
track me with Multifox enabled while in another tab. In fact, Multifox
doesn't even show up at all, or as active in the Firefox search bar, when I
visit other Google sites while logged in to Gmail for example!

It didn't used to...what happened? And thanks again for your efforts...

On Tue, Dec 18, 2012 at 3:16 PM, Jeferson Hultmann <notifications@github.com

**Comment by hultmann** [comment]
I'm not sure exactly about what you mean.

Could you please file another bug report describing observed results, expected results?

**Comment by bondbeau** [comment]
Yes, I did that now...please take a look and advise?
