### ISSUE TITLE
Multifox 2.0b4 Breaks vk.com messenger

### ISSUE THREAD

**Issue by PASAf** [hultmann/multifox#67]
With Multifox 2.0 Beta 4 I can't open a dialog in a messenger on vk.com and getting JavaScript error:

`JavaScript error: can't redefine non-configurable property 'localStorage'`

p.s. I'm using Firefox 15.0a2 (Aurora)

**Comment by hultmann** [comment]
Thanks, I'll investigate this issue before releasing beta 5.

**Comment by hultmann** [comment]
Fixed by #72
