### ISSUE TITLE
Discuz! forums logout in a period of time

### ISSUE THREAD

**Issue by fhoshino** [hultmann/multifox#7]
Using multifox 2.0b2 w/ Firefox 4.0.1,
I encounter a problem with forums using Discuz!, such as www.uwants.com,
after a period of time, it log me out automatically and I need to sign in again.

**Comment by hultmann** [comment]
This seems to be happening on multiple websites (e.g. Twitter). Cookies are expiring too fast.

**Comment by hultmann** [comment]
Resolving as duplicate of bug #16.
