### ISSUE TITLE
Multifox 1.3.3: Firefox 15 Keyboard Shortcut

### ISSUE THREAD

**Issue by rbaldwinuk** [hultmann/multifox#70]
Firefox 15 has a new "Responsive Design View" feature that can be enabled by using the keyboard shortcut Ctrl+Shift+M (the same keyboard shortcut as Multifox). This means that the Multifox shortcut no longer works.

**Comment by hultmann** [comment]
Thanks for the heads-up. It's so hard to find an available shortcut these days...

**Comment by hultmann** [comment]
Please try version 1.3.4 from https://github.com/hultmann/multifox/downloads

**Comment by rbaldwinuk** [comment]
Works great. Thanks a lot.

Wobbud

**Comment by seren** [comment]
FYI, on OS X the shortcut doesn't work. "Responsive Design View" on OS X is Command(accel)-Alt-M which this conflicts with. Setting line 122 in new-window.js to:
   key.setAttribute("modifiers", "control,alt");
fixes this (at least on OS X).

**Comment by hultmann** [comment]
@seren, now I'm using "control,alt" (for OS X only). Please test 1.3.4.1 from https://github.com/hultmann/multifox/downloads

**Comment by seren** [comment]
That works. Thanks.

**Comment by hultmann** [comment]
Thanks, released as 1.3.5.
