### ISSUE TITLE
Multifox 2b4 Breaks Facebook Chat/Messaging/Loading

### ISSUE THREAD

**Issue by mfmm** [hultmann/multifox#71]
The drop-down messages preview loads forever, along with opened conversations completely disabling messaging. Also completely disables the chat feature.

**Comment by hultmann** [comment]
I'm working on 2b5 and it seems to work fine with Facebook.  It will take a few more weeks until it gets released.

**Comment by warlock9k** [comment]
Hello. This bug isn't only in the Facebook. I have the same at the www.Mail.ru in main field of e-maile, also my online bank don't work correct and few other sites. So it will be very fine to get 2b5 earlier.

**Comment by hultmann** [comment]
warlock9k, some of this may be related to bug #72 as well.

**Comment by seren** [comment]
These localStorage/sessionStorage changes may be relevant:
https://bugzilla.mozilla.org/show_bug.cgi?id=754553
https://bugzilla.mozilla.org/show_bug.cgi?id=697903

Let me know if I can help (testing, etc).

**Comment by zmasterar** [comment]
It's the same for me, since yesterday all chat features are gone. I had to disable multifox 2b4.

This happend to me some time before, but i cleared cookies/cache and that fixed the problem, now even doing that it's still broken.

I hope u can work in 2b5 and release it quick, thanks a lot for the work.

**Comment by hultmann** [comment]
I'm working on getting a new version out ASAP.

**Comment by whombat** [comment]
I was about to say the same that Zmasterar posted. But the difference is that I have no any beta version. Facebook chat is not working for me and everytime I try to play my games it's telling me to delete junk and I have to set my scripts each time.
Thanks.

**Comment by hultmann** [comment]
@whombat 1.3.3 used to work but now is broken? Please try 1.3.4 from https://github.com/hultmann/multifox/downloads

**Comment by hultmann** [comment]
2b5 released. See bug #74. Is this bug fixed?

**Comment by zmasterar** [comment]
So far so good. With 2b5 now chat functionality is restore. Thanks a lot.
