### ISSUE TITLE
AWS Console components don't show up in Firefox 15 with Multifox 1.3.3

### ISSUE THREAD

**Issue by seren** [hultmann/multifox#72]
Multifox is great and was working fine until I upgraded Firefox from 14 to 15 (OS X 6). Now the Amazon Web Services console breaks in multifox-enabled windows, with much of the content missing. AWS still works in regular (non-profile identities) windows in version 1.3.3, however with version 2b4 all windows have profile identities, so AWS doesn't work at all. I've tried clearing my cache and disabling most extensions as well.

Here are screenshots of 1.3.3 in action:

[With Multifox](https://dl.dropbox.com/u/44088/multi-fox/with%20multi-fox.png)
[Without Multifox](https://dl.dropbox.com/u/44088/multi-fox/without%20multi-fox.png)

I have an unprivileged AWS test account you can test this with, if you need. Thanks.

-Seren

**Comment by hultmann** [comment]
Thanks for the report. How can I test it?

**Comment by seren** [comment]
https://477335754536.signin.aws.amazon.com/console
user: multifox-temp
pass: s%hou8]zjWFk

I'll leave this account active until you're done with it.

**Comment by hultmann** [comment]
I don't see any error message. This will require more investigation.

Gmail/Twitter seem to work fine. Have you noticed problems on other sites?

**Comment by seren** [comment]
I haven't but I do most of my browsing with 1.3.3 in non-profile identities windows. I just test gmail, gcal, and google+ and they all seem fine. Were you able to reproduce the missing content in the AWS console?

**Comment by seren** [comment]
And twitter seems ok.

**Comment by hultmann** [comment]
Yes, multifox-enabled windows are buggy.

**Comment by hultmann** [comment]
OK, localStorage support is broken (Multifox 1.x and 2.x). Let's find out why.

**Comment by seren** [comment]
Thanks. I've deleted the AWS account.

**Comment by hultmann** [comment]
Please try version 1.3.4 from https://github.com/hultmann/multifox/downloads
