### ISSUE TITLE
ETA on Multifox 2b5?

### ISSUE THREAD

**Issue by a-raccoon** [hultmann/multifox#74]
Last year I recall mention that development on Multifox 2 Beta would recommence in February 2012.  I'm wondering if this is still the case, and when we might expect 2 Beta 5 to arrive?

I'm so spoiled on Multifox 2 that I could never go back to 1.x again. ^_^

**Comment by zmasterar** [comment]
I agree, but [here](https://github.com/hultmann/multifox/issues/71#issuecomment-8148698), hultman said in a few weeks.

**Comment by hultmann** [comment]
Good news, folks. 2.0b5 is in good shape. My ETA is on or before September 15th.

I'm now removing restartless installation/update due to pending bugs.

**Comment by hultmann** [comment]
2.0b5 seems to work good enough now. Please try it from https://github.com/hultmann/multifox/downloads

.

**Comment by a-raccoon** [comment]
Dude.  You're pretty amazing.  just FYI

**Comment by hultmann** [comment]
Cool! Source code is not on github yet, I'm working on it.
