### ISSUE TITLE
2b5 elem is null

### ISSUE THREAD

**Issue by zds111** [hultmann/multifox#77]
时间戳: 2012/9/17 11:11:22
错误： elem is null
源文件：resource://multifox-modules/main.js
行：4070

use the code to load a sidebar,it can't work when I click the convert(转换) button,how to fix it?Thank you!the code of sidebar below:
var sidebar = document.getElementById("sidebar");
        var sidebarBox = document.getElementById("sidebar-box");
        var sidebarSplitter = document.getElementById("sidebar-splitter");
        //var text = document.commandDispatcher.focusedWindow.getSelection().toString();
        //var url = "http://translate.google.se/?text="+text;
        //var url = "http://translate.google.com.hk/?text="+text;
        var url = "http://javawind.net/tools/native2ascii.jsp?action=transform";
        if(sidebar.contentDocument.location != "about:blank" &&
        document.getElementById("sidebar-title").value == "Unicode" &&
        //(!text || sidebar.contentDocument.getElementById("web-panels-browser").getAttribute("cachedurl") == url)) {
        (sidebar.contentDocument.getElementById("web-panels-browser").getAttribute("cachedurl") == url)) {
            if(sidebarBox.hidden) {
                document.getElementById("viewWebPanelsSidebar").setAttribute("checked","true");
                sidebarBox.setAttribute("sidebarcommand", "viewWebPanelsSidebar");
                sidebarBox.hidden = sidebarSplitter.hidden = false;
            } else {
                document.getElementById("viewWebPanelsSidebar").removeAttribute("checked");
                sidebarBox.removeAttribute("sidebarcommand");
                sidebarBox.hidden = sidebarSplitter.hidden = true;
                content.focus();
            }
        } else {
        openWebPanel("Unicode", url);
        sidebarBox.width = 250;
        }

and the css code:
@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document regexp("http://javawind\.net/tools/native2ascii.*") {
@media all and (max-width: 37em) {
html body form table tbody tr td textarea
{
width:20em !important;
height:13em !important;

}

html body form table tbody tr td
{
float:left !important;
}
ul.nav,ol{display:none !important;}
}
}

**Comment by hultmann** [comment]
Hello, I'm not able to make this code work. Is there an extension I can install?

**Comment by zds111** [comment]
You can use this userChromejs(http://pan.baidu.com/share/link?shareid=63104&uk=939654632) to run(keypress:Shift+Alt+C) the code,I had wrote it down in the js.Maybe the Keyconfig addons also make it.

**Comment by hultmann** [comment]
Thanks, I already have a working fix. BTW, other way to reproduce this bug is by setting a bookmark to load in the sidebar.

**Comment by zds111** [comment]
Thank you!Expecting the new version
