### ISSUE TITLE
Identity profiles getting reset to default on firefox restart. [Multifox 1.3.5]

### ISSUE THREAD

**Issue by AquaDragonMew** [hultmann/multifox#79]
After restarting firefox with at least 3 different identity profiles, at least one of the windows changes to the default 1 identity profile instead of what it's supposed to be when loaded back up with no way to change it back, at least that I can find. It has happened on multiple occasions and only seems to go away if there are only 2 profiles open when closed.

**Comment by hultmann** [comment]
Is this a new bug in 1.3.5?

**Comment by othiym23** [comment]
I get this behavior reliably as of Multifox 2.2.0 – three windows for three Google profiles, and upon startup, the window that had tabs opened in the third profile resets to use the session from the first / default. A workaround is to close the whole window, open a new window in the correct (third) profile, and then reopen the just-closed window.

**Comment by hultmann** [comment]
Please try the version from
https://github.com/hultmann/multifox/issues/136#issuecomment-53949820
