### ISSUE TITLE
Embedded vimeo videos show black boxes

### ISSUE THREAD

**Issue by dnyanesh** [hultmann/multifox#8]
I know this is a very strange issue but it is true. The day I installed Multifox 2 Beta, the embedded vimeo videos started showing black boxes. I updated my flash tried disabling ad blocking addons but couldn't solve the issue. I then disabled the addons I had installed the previous day and by trial and error method I zeroed in on multifox 2 beta which came out to be the culprit. I am using Firefox 4.0.1 and the latest flash build.

**Comment by hultmann** [comment]
It happens with YouTube embedded videos as well. A workaround: remove vimeo/youtube accounts.

**Comment by hultmann** [comment]
Is this still happening? I can't reproduce it anymore.

**Comment by dnyanesh** [comment]
I stopped using Multifox Beta and I switched back to Multifox stable version, which made the problem go.

**Comment by hultmann** [comment]
I believe this issue has been fixed since version 2b5. Could you confirm it, please?
