### ISSUE TITLE
The logout account still display?

### ISSUE THREAD

**Issue by taglife** [hultmann/multifox#80]
Issue:
1. The logout account still display?
2. It can be displayed in the add-ons bar? or tool bar?

Suggest:
3. Why not on the AMO?
4. v2 icon are too ugly?
5. v2 icon text too wide?
Thank you :)

**Comment by hultmann** [comment]
Are all these questions about Multifox 2?

> 1. The logout account still display?

hmmm What Logout display?

**Comment by taglife** [comment]
Yes version 2 beta.

You login account in logout still display.

**Comment by hultmann** [comment]
> 1. The logout account still display?

It is hard to figure out when an user is logged out. Multifox doesn't even try.

> 1. It can be displayed in the add-ons bar? or tool bar?

Do you mean the username label? No. (I think it fits better in the URL bar.)

> 1. Why not on the AMO?

Ii will happen eventually.

> 1. v2 icon are too ugly?

well, I'm not a designer.

> 1. v2 icon text too wide?

bug #84?

**Comment by taglife** [comment]
Answer1: What is mean?

Answer2: Yes, Hope can customize the location.

Answer5: This 122px...
![multifox-2.0b6.png](https://lh5.googleusercontent.com/-jXGN_4SXaSw/UJYhzQ0dAOI/AAAAAAAAE50/Nz1hZg5Esz0/s470/multifox-2.0b6.png)

multifox-2.0b6 modify :P 
![multifox-2.0b6-modify.png](https://lh4.googleusercontent.com/-GhEj4BViiSc/UJYlMHX5BUI/AAAAAAAAE6M/jxiZH_VEuzI/s150/multifox-2.0b6-modify.png)

**Comment by Drugoy** [comment]
@hultmann 

> It is hard to figure out when an user is logged out. Multifox doesn't even try.

How about adding a pseudo-account "log out" to the list of the user's existing accounts? It could work like just isolating all the accounts' cookies, so you would start using new, fresh cookies.

Switching to that pseudo-account would do 2 good things: the user will be actually logged out from that site and thus, the things like 'facebook +1' won't track your browsing activity on the 3rd party sites (I mean cookies-tracking, because, of course, they still can track you by your IP or client's data).

Should I open a new issue for that?

**Comment by hultmann** [comment]
> Answer1: What is mean?

I'm afraid I still didn't understand your question from first comment...

> Answer5: This 122px...

Currently I use 50ch, but it seems to not work for all fonts.

(Closing this issue since there is nothing to be done here. Please create new issues for your various requests.)

**Comment by hultmann** [comment]
> How about adding a pseudo-account "log out" to the list of the user's existing accounts? It could work like just isolating all the accounts' cookies, so you would start using new, fresh cookies.
> 
> Switching to that pseudo-account would do 2 good things: the user will be actually logged out from that site and thus, the things like 'facebook +1' won't track your browsing activity on the 3rd party sites (I mean cookies-tracking, because, of course, they still can track you by your IP or client's data).

The tracking for logged in sites can be avoided in 2.0b7 (because you'll be able to set Facebook/Twitter/Google to be logged out for 3rd-party elements).

> Should I open a new issue for that?

Yep (or wait for 2.0b7 to see how it will work).
