### ISSUE TITLE
Feature for disable functionality by domain

### ISSUE THREAD

**Issue by MurzNN** [hultmann/multifox#81]
Please add feature for disable this module on specific domains! It works well on many sites, but totally broke functionality on other sites. Maybe those problems can be fixed in future versions, but I can't wait, I want to use it today, but broken auth on some sites is critical for me and I must disable this extension. 

Disabling will be good to implement via mask or regexp, so we can enable it on all subdomains.

Another way to fix this problem is adding button "Enable multi login" for each domain (with disable option too), so before this button isn't pressed, firefox works like without this module, but when pressed - multifox activate his functionality.

**Comment by seren** [comment]
You could try multifox 1.3.5. That version is only enabled when you open a new Identity Profile window.

**Comment by MurzNN** [comment]
I know about multifox 1.x version, but it is not comfortable for using, because it creates profiles globally, not per-site, and I need to open new window. multifox 2.x UI is much better, but it have problems on some sites. So adding disable functionality for multifox 2.x will be best solution.

**Comment by hultmann** [comment]
This will be addressed by #14 (whitelist)
