### ISSUE TITLE
How secure is the add-on?

### ISSUE THREAD

**Issue by fourmi4x** [hultmann/multifox#83]
Hi, I would love to use this add-on but I couldn't find any information related to how secure it is.

Could the login/password be stolen during switching or saving of accounts?
Where are they stored?
Is everything encrypted?

I'm not a security expert at all... but as I may be using this for sensitive accounts, I would love to find some explanations of the process.

**Comment by hultmann** [comment]
Hello,

> Could the login/password be stolen during switching or saving of accounts?
> Where are they stored?
> Is everything encrypted?

Multifox does not store passwords (or automatically send any data to any other computer).

The data Multifox needs (like cookies) is stored along with the data Firefox usually would use (without Multifox). No new files are created.

**Comment by fourmi4x** [comment]
Thank you for these precisions
