### ISSUE TITLE
Host add-on on addons.mozilla.org

### ISSUE THREAD

**Issue by Drugoy** [hultmann/multifox#85]
Why this extension is not listed on AMO?
Every add-on there gets some quite good validation before it gets accepted, so users would feel more protected, if you'd host your add-on there.

**Comment by hultmann** [comment]
That's the plan for 1.4.

**Comment by tbs** [comment]
I beat this add-on (v2) will be the most popular in AMO pages in few months.

**Comment by Drugoy** [comment]
@hultmann why there is no such a plan for v2?

**Comment by hultmann** [comment]
yes, if I manage to get 2.0 done. :-P 1.x is way easier.

**Comment by hultmann** [comment]
Multifox 2.0.6 finally reviewed: https://addons.mozilla.org/firefox/addon/multifox/

P.S. for now, no plans to submit the other Multifox (beta) to AMO.

**Comment by tbs** [comment]
Right, which is the last version: Multifox 2.0.6 (AMO) or Multifox 2.0b8?

**Comment by Drugoy** [comment]
@hultmann could you rename Multifox beta to "Multifox tabbed"?
By doing so - you could avoid the currently existing confusion between these 2 versions.

**Comment by hultmann** [comment]
> Right, which is the last version: Multifox 2.0.6 (AMO) or Multifox 2.0b8?

both!

> could you rename Multifox beta to "Multifox tabbed"?

the new name won't have "Multifox" in it. I expect to release 2.0b9 in a few weeks, hopefully with the new name.

**Comment by Drugoy** [comment]
> the new name won't have "Multifox" in it.

then how will you call it? Do you plan to upload it to AMO for a review anyhow soon?

**Comment by Drugoy** [comment]
I hate multiple windows in the browser: I use only a single one (except for the cases I need to see 2 pages at the same time), so I don't use the "windowed" version of Multifox.
But due to lots of bugs in the "tabbed" version - I've switched it off for now :(

**Comment by hultmann** [comment]
> then how will you call it? 

to be decided.

> Do you plan to upload it to AMO for a review anyhow soon?

no.

> But due to lots of bugs in the "tabbed" version - I've switched it off for now :(

Are you referring to #124?
