### ISSUE TITLE
Disable automatic detection of login

### ISSUE THREAD

**Issue by wfaulk** [hultmann/multifox#86]
I don't want Multifox to automatically detect logins.  I just want to set one tab as having a different login for one specific web site.  I don't want to be able to switch between profiles in one tab.  All of the additional features, while nice, I'm sure, for some people, just don't work well for me and get in my way.  In fact, they have caused problems when trying to log into multiple sites on the same domain.

While it would be good for you to fix those bugs, I still think it's overkill for what a lot of us want to do.  I don't really want Multifox to remember all my different logins.  I just want to be able to separate one from another.

**Comment by hultmann** [comment]
Isn't it the same issue as bug #81?
