### ISSUE TITLE
MultiFox accesible by context menu for popups

### ISSUE THREAD

**Issue by tbs** [hultmann/multifox#88]
In some popups (Google accounts/OpenID don't remember), you can't change login to authorize access. So maybe unique solution is to make MultiFox accessible by context menu. What do you think?

Other minor question, version 2.0 final will be restartless?

**Comment by tbs** [comment]
ok ignore this report, my config "dom.disable_window_open_feature.location" was false (remove urlbar from popup window). I'm a rare case.

**Comment by hultmann** [comment]
> Other minor question, version 2.0 final will be restartless?

yes. Actually current source on github already is (it is a bit buggy though).

**Comment by Drugoy** [comment]
> yes. Actually current source on github already is (it is a bit buggy though).

Seriously? That's an awesome news!
