### ISSUE TITLE
Beta 2.0b2 problem with Google ToolBar

### ISSUE THREAD

**Issue by Botixete** [hultmann/multifox#9]
Configuration:
- Firefox Version: 4.0.1
- Multifox Version: Beta 2.0b2
- Google Toolbar Version: 7.1.20110316W

Scenario:
- When you try to login from the Google Toolbar icon (so the Bookmarks button, etc, begin to work), a popup windows appear and you introduce your account data. After accept, in the Google Toolbar you must see a green circle telling you that you are logged.

Problem:
- After successfully login, the username is correctly showing in the address bar (as with other web services). But the Google Toolbar is saying that you are not logged in. The circle (that must be green) is still in gray, and the login button says "Connect" (and must by showing the username used to login).
- I have tested with other versions of the Google Toolbar and the result is the same.
- I have tested that, with all the versions tested, disabling Multifox makes this problem disappear.

Sorry for my English (Spanish user here).

**Comment by Botixete** [comment]
More data:
- Have been testing it a while more, and I have found a reasonable trick that solve the problem temporarily. The trick is that you must check the "Keep logged in" (permanecer conectado in Spanish) when login with your Google Account.
  You will not see the green circle and you won't be able to use the Toolbar normally, but if you close and reopen Firefox, you will be logged automatically and the Toolbar and Multifox will work correctly.
- I think it's a reasonable solution if you are not using a shared computer.

**Comment by hultmann** [comment]
Probably the same bug as #15. This will be hard to fix.

**Comment by hultmann** [comment]
Closing, Google won't develop Toolbar for Firefox anymore. http://googletoolbarhelp.blogspot.com/2011/07/update-on-google-toolbar-for-firefox.html
